### ISSUE TITLE
packaging bug

### ISSUE THREAD

**Issue by Zablonski** [KSP-CKAN/CKAN-meta#1021]
File           : Ships/VAB/RSB Ares I.craft
Installing Mod : RealScaleBoosters 0.8.1
Owning Mod     : RealismOverhaul
CKAN Version   : v1.16.1-0-g2e91715 (beta)

**Comment by politas** [comment]
What is going wrong in this case?

**Comment by politas** [comment]
@Zablonski , does that issue address the problem as you see it? RealismOverhaul manage their own metadata, so it needs to be raised over there.

**Comment by Zablonski** [comment]
Thanks, that certainly looks like it - I'll go annoy them.
