### ISSUE TITLE
kerbalstuff.com defunct

### ISSUE THREAD

**Issue by tsal** [KSP-CKAN/CKAN-meta#1030]
Not sure if this is the right place to discuss this, but I'm forking the kerbalstuff.com source code and will be setting up a repository as soon as I can to try to replace the functionality.

Was anyone able to get the data torrent? This impacts more than a handful of mods it looks like.  The index still lists some packages as available there, but the repository is no longer there.  Google cache shows there was some warning, but it looks like it's been down completely for about a week.

If this is the wrong place, and someone knows where this discussion is on-going already or efforts already started, please let me know and close this.

**Comment by plague006** [comment]
You are quite late to this party.

http://spacedock.info/

https://github.com/KSP-CKAN/CKAN/issues/1586

**Comment by tsal** [comment]
Thanks - I came here to close my own issue when I found SpaceDock; so it's up to the mod owners to update their URLs in the index.

**Comment by politas** [comment]
Not entirely. We are updating mods as we find out about them.
