### ISSUE TITLE
package colision?

### ISSUE THREAD

**Issue by miki-g** [KSP-CKAN/CKAN-meta#1031]
File           : GameData/kdufferskorp/race wheel/fe0_wheel.png
Installing Mod : kdufferskorpracewheel 1.0
Owning Mod     : KduffersMultiwheels
CKAN Version   : v1.16.1-0-g2e91715 (beta)

**Comment by miki-g** [comment]
KduffersMultiwheels contains kdufferskorpracewheel ...
http://forum.kerbalspaceprogram.com/index.php?/topic/119150-kduffers-multi-wheels-kmw/#comment-2243834

... is possible add to ckan informations about "multipacking" mods like this mod to avoid similarly problems?

**Comment by politas** [comment]
Waiting on merging for solution
