### ISSUE TITLE
NetKAN: "Could not find KSPChromaControl entry in zipfile to install"

### ISSUE THREAD

**Issue by cguckes** [KSP-CKAN/CKAN-meta#1056]
I'm getting the above mentioned error when using netkan to compile the following file:

```
{
    "spec_version"    : 1,
    "identifier"      : "KSPChromaControl",
    "$kref"           : "#/ckan/github/cguckes/ksp-chroma",
    "license"         : "GPL-3.0",
    "name" : "KSP Chroma Control",
    "abstract" : "Lights up your keyboard to show you all the functions your vessel actually has.",
    "resources" : {
        "homepage" : "https://github.com/cguckes/ksp-chroma",
        "repository"  : "https://github.com/cguckes/ksp-chroma"
    }
}

```

my zip file contains just one folder (the one it claims not to find). Do I need to restructure my zip file?

**Comment by plague006** [comment]
In local testing I don't run into any issues.

For the `abstract` you should make very clear that users require Synapse (Razor Synapse I imagine?). You must also specify KSP compatibility via either a single `ksp_version` or a range via `ksp_version_min` and `ksp_version_max`.

**Comment by cguckes** [comment]
I added all the changes you requested, but I'm still getting the error

> 1214 [1] FATAL CKAN.NetKAN.Program (null) - Could not find KSPChromaControl entry in zipfile to install

I attached the file. If you can netkan it without much trouble I'd appreciate if you could add it for me. Thanks in advance :-)
