### ISSUE TITLE
RasterPropMonitor conflicts with RasterPropMonitor Core, yet hard-requires the latter

### ISSUE THREAD

**Issue by YellowApple** [KSP-CKAN/CKAN-meta#1057]
File           : GameData/JSI/JSIAdvTransparentPods/Plugins/Config.cfg
Installing Mod : RasterPropMonitor-Core v0.25.0
Owning Mod     : RasterPropMonitor
CKAN Version   : v1.16.1-0-g2e91715 (beta)

Happens when attempting to install RasterPropMonitor on KSP 1.1.

**Comment by plague006** [comment]
Thanks for the heads up, this will be fixed via https://github.com/KSP-CKAN/NetKAN/pull/3617.
