### ISSUE TITLE
Unable to install RasterPropMonitor for KSP 1.1

### ISSUE THREAD

**Issue by bombaatu** [KSP-CKAN/CKAN-meta#1059]
File: GameData/JSI/JSIAdvTransparantPods/Plugins/Config.cfg
Installing Mod: RasterPropMonitor-Core v0.25.0
Owning Mod: RasterPropMonitor
CKAN Version: v1.16.1-0-g2e91715 (beta)

KSP 1.1 (Release version, Steam), fresh install

**Comment by TheGreenDragon** [comment]
Same here.  RPM-Core installs fine by itself.

File: GameData/JSI/JSIAdvTransparentPods/Plugins/Config.cfg
Installing Mod: RasterPropMonitor-Core v0.25.0
Owning Mod: RasterPropMonitor
CKAN Version: v1.16.1-0-g2e91715 (beta)

**Comment by jacejfrancis** [comment]
Same problem here.  KSP 1.1.

File           : GameData/JSI/JSIAdvTransparentPods/Plugins/Config.cfg
Installing Mod : RasterPropMonitor-Core v0.25.0
Owning Mod     : RasterPropMonitor
CKAN Version   : v1.16.1-0-g2e91715 (beta)

**Comment by plague006** [comment]
Thanks for the heads up, this will be fixed via https://github.com/KSP-CKAN/NetKAN/pull/3617. The change will take effect within 3 hours of the merge.

**Comment by plague006** [comment]
With 0d6b17edc41c3896d228e4fcb9c979fc891cf7c5 comitted, the change should now be live and installations should now go smoothly. Please let me know if that isn't the case.
