### ISSUE TITLE
Adding ForScience!

### ISSUE THREAD

**Issue by WaveFunctionP** [KSP-CKAN/CKAN-meta#1074]
I've been getting regular request to add my mod ForScience!. I'm currently published on curse.

http://mods.curse.com/ksp-mods/kerbal/220264-for-science

I don't how all of this works, but if possible, I would like for ckan to simply publish the latest version from curse.

**Comment by plague006** [comment]
We have an [open PR](https://github.com/KSP-CKAN/CKAN/pull/1608) that will allow CKAN to automatically scrape curse for new releases but presently we can only automatically scrape new releases from SpaceDock and GitHub.

That being said, any time we're made aware of a new version/release of your mod we'll be happy to manually index it. As soon as https://github.com/KSP-CKAN/CKAN-meta/pull/1075 is reviewed and merged, the mod will be available via CKAN.

**Comment by WaveFunctionP** [comment]
Thank you kindly. :)

**Comment by plague006** [comment]
My pleasure, thanks for the heads up about the mod not being indexed.
