### ISSUE TITLE
1.1 plugins waiting to be updated on CKAN :

### ISSUE THREAD

**Issue by labo-css** [KSP-CKAN/CKAN-meta#1078]
- [x] http://forum.kerbalspaceprogram.com/index.php?/topic/54284-11-extraplanetary-launchpads-v530/

- [x] http://forum.kerbalspaceprogram.com/index.php?/topic/55420-110-toolbar-1711-common-api-for-draggableresizable-buttons-toolbar/

- [x] http://forum.kerbalspaceprogram.com/index.php?/topic/91806-achievements-180-earn-145-achievements-while-playing-ksp-11-4202016/

- [x] Not yet on CKAN : http://forum.kerbalspaceprogram.com/index.php?/topic/135395-11-makeitsmall-11-because-sometime-you-need-stuff-to-be-smaller/

I am not familiar with CKAN team pratices, how do i can help?

**Comment by plague006** [comment]
A starting point: https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN
