### ISSUE TITLE
Hullcam VDS & Achievements

### ISSUE THREAD

**Issue by labo-css** [KSP-CKAN/CKAN-meta#1088]
Don't find any download link for it (other than curse), but the file is ready if you got one : https://github.com/labo-css/CKAN-meta/blob/master/HullcamVDS/HullcamVDS-0.52.ckan

Same deal with this one : 
https://github.com/labo-css/CKAN-meta/blob/master/Achievements/Achievements-1.9.0.ckan

**Comment by labo-css** [comment]
Fixed the Hullcam file, what should i do for the achievements?

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/NetKAN/pull/3669 addressed achievements
