### ISSUE TITLE
KSP-AVC is outdated for 1.1

### ISSUE THREAD

**Issue by d-faure** [KSP-CKAN/CKAN-meta#1089]
Cf. http://forum.kerbalspaceprogram.com/index.php?/topic/72169-11-ksp-avc-add-on-version-checker-plugin-1161-miniavc-ksp-avc-online-2016-04-19/
> NOTE: Version 1.1.5 works in all 1.0 versions of KSP. Use 1.1.6 for KSP 1.1 and later

**Comment by plague006** [comment]
Addressed by https://github.com/KSP-CKAN/NetKAN/pull/3673
