### ISSUE TITLE
Stock Visual enhancements

### ISSUE THREAD

**Issue by rnrsr** [KSP-CKAN/CKAN-meta#1094]
Hello,

I've tried removing the clouds.cfg file stated below (and restarted CKAN) but I still get this error:

> Oh no! We tried to overwrite a file owned by another mod!
> Please try a `ckan update` and try again.
> 
> If this problem re-occurs, then it maybe a packaging bug.
> Please report it at:
> 
> https://github.com/KSP-CKAN/CKAN-meta/issues/new
> 
> Please including the following information in your report:
> 
> File           : GameData/StockVisualEnhancements/EVE/Atmosphere/clouds.cfg
> Installing Mod : StockVisualEnhancements 1:0.6.4
> Owning Mod     : SVE-UltraResolution
> CKAN Version   : v1.16.1-0-g2e91715 (beta)

I've added my .ckan - any suggestions?

[mods.zip](https://github.com/KSP-CKAN/CKAN-meta/files/232574/mods.zip)

**Comment by plague006** [comment]
`StockVisualEnhancements 1:0.6.4` is for KSP 1.1
`SVE-UltraResolution` doesn't exist for KSP 1.1.

You need to uninstall `SVE-UltraResolution` completely then update `StockVisualEnhancements`

**Comment by politas** [comment]
Yep. There are no configuration options now. Use all the memory!
