### ISSUE TITLE
Mk3 Hypersonic Systems Installs to Incorrect Path

### ISSUE THREAD

**Issue by Symmaethus** [KSP-CKAN/CKAN-meta#1105]
CKAN installs this mod to Gamedata/Mk3HypersonicSystems/Mk3HypersonicSystems.  I looked over the meta-data and couldn't find the problem.  Though I am brand new at this.

https://github.com/KSP-CKAN/CKAN-meta/blob/master/Mk3HypersonicSystems/Mk3HypersonicSystems-1-1.1.0.1.ckan

**Comment by plague006** [comment]
Have you upgraded to `1:1.1.0.1` of the mod?

**Comment by Symmaethus** [comment]
THAT'S why I didn't see any issues.  I had a the CKAN client was using a cached version of the old mod (1.1.0.1) while I was looking at the meta-data for the newest.  Looks like it's fixed.
