### ISSUE TITLE
Outdated mods

### ISSUE THREAD

**Issue by racer01** [KSP-CKAN/CKAN-meta#1134]
**KerBalloons** is outdated (v0.3.2 on ckan while v0.3.4 is already released), and broken (download URL not found). 
http://kerbal.curseforge.com/projects/kerballoons-v0-3-4
http://forum.kerbalspaceprogram.com/index.php?/topic/107432-112-kerballoons-v034-balloons-for-ksp/

**Kerbal Planetary Base Systems** is also updated to v1.0.10
https://github.com/Nils277/KerbalPlanetaryBaseSystems/releases/tag/1.0.10
http://forum.kerbalspaceprogram.com/index.php?/topic/133606-112-kerbal-planetary-base-systems-v1010-updated-2nd-may-16/

**Comment by plague006** [comment]
You have very strange timing: https://github.com/KSP-CKAN/CKAN-meta/pull/1133

**Comment by plague006** [comment]
#1135 will address KerBalloons. Kerbal Planetary Base Systems will need a cache flush of `KerbalPlanetaryBaseSystems`. @techman83

**Comment by plague006** [comment]
Closed by https://github.com/KSP-CKAN/CKAN-meta/pull/1143
