### ISSUE TITLE
Trying to overwrite file owned by another mod

### ISSUE THREAD

**Issue by Scoundrel666** [KSP-CKAN/CKAN-meta#1147]
Please note that this repository's issues section will be closed in the near future.

Please open metadata-related issues (issues relating to incorrect information about mods, missing versions, or incorrect installations) in the NetKAN repository (https://github.com/KSP-CKAN/NetKAN/issues) or if you want to suggest something or report a bug relating to CKAN as a whole, open the issue in the CKAN repository (https://github.com/KSP-CKAN/CKAN/issues).

File           : GameData/scatterer/sunflare/Ghost1.png
Installing Mod : AstronikiSunflareforScatterer 1.0
Owning Mod     : Scatterer
CKAN Version   : v1.16.1-0-g2e91715 (beta)

**Comment by plague006** [comment]
Uninstalling and re-installing  scatterer will clear this issue.
