### ISSUE TITLE
.90 Mod Updates

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN-meta#125]
/cheer Squad

KSP's in Beta!

/cheer Squad

This is a general thread to track which mods have been updated to .90, but haven't been updated in CKAN.

I've yet to audit the entire list, but the ones that I've seen thus far are:
- [x] Docking Port Alignment Indicator
- [x] Station Science
- [x] Tweak Scale
- [X] Universal Storage
- [X] Universal Storage (KAS Pack)
- [x] USI Kolonization 
- [x] USI Asteroid Recycling
- [x] USI Freight Transport Technologies
- [x] USI Exploration Pack
- [X] USI Survival Pack
- [X] Bargain Rockets
- [x] Distant Object Enhancement
- [X] FASA Launch Clamps
- [x] Kerbal Konstructs
- [x] KSP AVC
- [x] Notepad
- [x] QuickExit
- [x] QuickHide
- [x] Resource Overview
- [X] Simple Docking Indicator by mic_e
- [X] SXT

Edit:
Is there an automated script that hasn't ran that will update everything hosted on Github and KerbalStuff?

**Comment by PickledTripod** [comment]
There's also the issue of 0.25 mods that are still compatible with 0.90, like most parts mods. For exemple I had to install manually Nertea's Mk4 Spaceplane System and Stockalike Station Parts Extensions and they work just fine, shouldn't they be marked as 0.90 even thought they haven't been officially updated by the author?

**Comment by sargunster** [comment]
I've heard KW Rocketry is also compatible.

**Comment by Ippo343** [comment]
shouldn't they be marked as 0.90 even thought they haven't been officially updated by the author?

No. Unless the author explicitly confirms that the mod is still compatible, we should not make this assumptions.

**Comment by PickledTripod** [comment]
[Nertea did confirm](http://forum.kerbalspaceprogram.com/threads/91814-0-25-Stockalike-Station-Parts-Expansion-%2817-11-2014-CTT-compatibility%29/page23#230) that Stockalike Station Parts Extensions works with 0.90 on the KSP forums. For the Mark IV parts I can't find a post from him saying specifically "the mod is still compatible", but he does [recommands upgrading to 0.90](http://forum.kerbalspaceprogram.com/threads/101699-0-25-Mark-IV-Spaceplane-System-%2814-12-14-important-fixes!%29/page34#339) to make it easier to mount wings on the Mk4 fuselage. And it's been tested by a lot of users.

>I've heard KW Rocketry is also compatible.
I would be surprised if it weren't, again it's only a parts pack. However the devs haven't said anything about 0.90 yet and some people are waiting for that to upgrade.

**Comment by khorn** [comment]
Porkjet's Habitat Pack hasn't been updated, but various posters in the mod thread say it works in 0.90.

FYI

**Comment by hakan42** [comment]
Still, usually we go with the decisions of the mod authors themselves.

**Comment by PickledTripod** [comment]
I understand that but CKAN is intended to be a tool to make modding easier for players. Ideally I would use only CKAN to manage my mods but it's not possible if updates break compatibility every few months. If a mod is feature complete and unaffected by updates it can take a while before the author updates it.

A solution would be to allow installing mods, with a warning message to make sure players undestand that it might break their game.

**Comment by hakan42** [comment]
@PickledTripod , I understand you too :smile: 

Would you mind terribly to go to https://github.com/KSP-CKAN/CKAN-support/issues and write an enhancement request? There, we can discuss this without polluting the ".90 Mod updates" issue :smiling_imp:

**Comment by hakan42** [comment]
This is more than two weeks old now, let's open up a new one when KSP 1.0 is released :smile:
