### ISSUE TITLE
Transfer Window Planner

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN-meta#175]
This is a solid mod to add to KSP-CKAN.

Useful information:
Author:
TriggerAu

Abstract:
The Transfer Window Planner is a plugin to let you visualise planetary transfer efficiency in-game. 

License:
This work is licensed under an MIT license as outlined at the OSI site

Dependencies:
None.  However, if Toolbar is present, it will allow you to use the same button that's on the stock toolbar.

Relevant links:
Forum Post:
http://forum.kerbalspaceprogram.com/threads/93115

GitHub:
https://github.com/TriggerAu/TransferWindowPlanner

Curse:
http://kerbal.curseforge.com/ksp-mods/224116

KerbalStuff:
https://kerbalstuff.com/mod/268

**Comment by hakan42** [comment]
Is available via ckan now, closing.
