### ISSUE TITLE
Active Texture Management not updating version.  Still showing 1.0, should be 4.3

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-meta#195]
_From @radinator on December 26, 2014 8:36_

Homepage shows correctly, but gets very old version.  Also, ATM has a GitHub page https://github.com/rbray89/ActiveTextureManagement/releases/tag/4-3

_Copied from original issue: KSP-CKAN/CKAN#696_

**Comment by hakan42** [comment]
By his own comment, Teonlight is not the author of the mod but just the uploader.

The kref needs to be switched to github, but with ATM having multiple zip files per release, we need a way to filter them. Maybe this is another use case for KSP-CKAN/CKAN-netkan#22 ?
