### ISSUE TITLE
AdvancedJetEngine Duplicate Identifier

### ISSUE THREAD

**Issue by BasharMilesTeg** [KSP-CKAN/CKAN-meta#217]
AdvancedJetEngine has two different identifiers:
'AJE' as seen here [.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/AJE-1.7a.ckan)
'AdvancedJetEngine' as seen here [.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/AdvancedJetEngine-2.0.2.ckan) [.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/AdvancedJetEngine.netkan)
the 'AJE' identifier is used by Realism Overhaul [.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/RealismOverhaul.netkan)

**Comment by hakan42** [comment]
The reference from Realism Overhaul is fixed.

What do we do with the "old" AJE ckans? Delete them? Are we able to provide an upgrade path to "AdvancedJetEngine"?

**Comment by BasharMilesTeg** [comment]
This is what I did when I was fixing pwing:
[Issue](https://github.com/KSP-CKAN/CKAN-meta/issues/191) [NetKAN](https://github.com/KSP-CKAN/NetKAN/pull/349) [CKAN-meta](https://github.com/KSP-CKAN/CKAN-meta/pull/210)

**Comment by TeddyDD** [comment]
We should at least change descriptions and name of old AJE ckans to something that shows they are 
deprecated
