### ISSUE TITLE
Update Universal Storage Mod Error

### ISSUE THREAD

**Issue by draugar** [KSP-CKAN/CKAN-meta#219]
I tried updating the mod through CKAN and it gives me the following error.

GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.3-0-g0000000 (beta)

**Comment by reseune** [comment]
I submitted this as an issue as well; however, it is due to Universal Storage being updated today and the previous modpacks (KAS, TAC, etc) being deprecated. I closed my issue and believe this one should also be closed.

**Comment by AlexanderDzhoganov** [comment]
UniversalStorage-KAS is deprecated, you should not install it anymore.
