### ISSUE TITLE
Error while installing Universal Storage - KSP pack

### ISSUE THREAD

**Issue by WolfHealr** [KSP-CKAN/CKAN-meta#220]
File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.3-0-g0000000 (beta)

**Comment by khorn** [comment]
I've seen this issues as well.  This is the first file to cause a problem, but others also fail, including the model.mu and part.cfg file for the KAS Container wedge, as well as the files for the EVAX part.

**Comment by khorn** [comment]
Aha.  It looks like as of the most recent release of Universal Storage, the add on packs are no longer a thing, so the KSP addon mo longer needs to be installed.  So the solution when having a problem installing this pack is...to not install it.

**Comment by khorn** [comment]
Is there a way to update the metadata for the KAS addon pack to mark it as incompatible with Universal Storage mod with versions >= 1.0.91.1?  If so, that's probably what needs to be done here.

**Comment by sargunster** [comment]
Maybe with something like:

```
"conflicts" : [
    { "name" : "UniversalStorage",   "min_version" : "1.0.90.1" }
]
```

I'm not sure if `conflicts` supports version numbering though.

**Comment by AlexanderDzhoganov** [comment]
UniversalStorage-KAS is deprecated, you should not install it anymore.
