### ISSUE TITLE
Can't install Universal Storage KAS Pack

### ISSUE THREAD

**Issue by mjones1052** [KSP-CKAN/CKAN-meta#221]
When trying to install US KAS pack, as of recent update, it won't install due to:

: GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.3-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

This worked prior.

**Comment by sargunster** [comment]
KAS Pack is no longer needed with the latest version of Universal Storage. US now includes all the packs and enables them depending on which mods are installed.

**Comment by AlexanderDzhoganov** [comment]
UniversalStorage-KAS is deprecated, you should not install it anymore.
