### ISSUE TITLE
Universal Storage [KAS PACK] overwrite error

### ISSUE THREAD

**Issue by mazedesign** [KSP-CKAN/CKAN-meta#230]
File : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod: UniversalStorage 1.0.90.1
Owning Mod : UniversalStorage-KAS
CKAN Version : v1.5.3-0-g0000000 (beta)

manually removing file triggers other errors:

File           : GameData/UniversalStorage/Parts/US_3R310_EVA_EVAX/EVAX.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.3-0-g0000000 (beta)

manually removing file triggers other errors:

The following inconsistecies were found:
UniversalStorage-KAS wishes to install GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga, but this file is registered to UniversalStorage
 * UniversalStorage-KAS wishes to install GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/model.mu, but this file is registered to UniversalStorage
 * UniversalStorage-KAS wishes to install GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/part.cfg, but this file is registered to UniversalStorage
 * UniversalStorage-KAS wishes to install GameData/UniversalStorage/Parts/US_3R310_EVA_EVAX/EVAX.tga, but this file is registered to UniversalStorage
 * UniversalStorage-KAS wishes to install GameData/UniversalStorage/Parts/US_3R310_EVA_EVAX/model.mu, but this file is registered to UniversalStorage
 * UniversalStorage-KAS wishes to install GameData/UniversalStorage/Parts/US_3R310_EVA_EVAX/part.cfg, but this file is registered to UniversalStorage

**Comment by mazedesign** [comment]
nevermind, duplicate of #220, sorry.

**Comment by AlexanderDzhoganov** [comment]
UniversalStorage-KAS is deprecated, you should not install it anymore.
