### ISSUE TITLE
issue installing realism Overhaul

### ISSUE THREAD

**Issue by parsala** [KSP-CKAN/CKAN-meta#233]
Downloading "https://kerbalstuff.com/mod/52/Ferram Aerospace Research/download/v0.14.6"
Downloading "https://kerbalstuff.com/mod/418/Active Texture Management/download/1.0_x86"
Downloading "https://kerbalstuff.com/mod/11/Connected Living Space/download/1.1.0.0"
Downloading "http://addons.cursecdn.com/files/2216/818/KSP-AVC-1.1.5.0.zip"
Downloading "https://github.com/NathanKell/ProceduralWings/releases/download/v0.9.3/Procedural_Wings-0.9.3.zip"
Downloading "https://github.com/e-dog/ProceduralFairings/releases/download/v3.11/ProcFairings_3.11.zip"
Downloading "https://github.com/Swamp-Ig/ProceduralParts/releases/download/v0.9.21/ProceduralParts-0.9.21.zip"
Downloading "https://kerbalstuff.com/mod/71/RealChute Parachute Systems/download/1.2.6.3"
Downloading "https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/download/v1.5.2/RemoteTech-1.5.2.zip"
Downloading "https://kerbalstuff.com/mod/150/TextureReplacer/download/2.1.2"
Downloading "https://nabaal.net/files/ksp/nathankell/RealSolarSystem/Textures/RSSTextures4096DDS.zip"
Module "Advanced Jet Engine (AJE)" successfully installed
Module "Crossfeed Enabler" successfully installed
Module "DDSLoader" successfully installed
Module "Ferram Aerospace Research" successfully installed
Module "Kerbal Joint Reinforcement" successfully installed
Module "Module Manager" successfully installed
Module "ModuleRCSFX" successfully installed
Module "Real Fuels" successfully installed
Module "Realism Overhaul" successfully installed
Module "Real Solar System" successfully installed
Module "Active Texture Management" successfully installed
Module "Connected Living Space" successfully installed
Module "Deadly Reentry Continued" successfully installed
Module "KSP AVC" successfully installed
Module "MechJeb 2" successfully installed
Module "Procedural Wings" successfully installed
Module "Procedural Fairings" successfully installed
Module "Procedural Parts" successfully installed
Module "RealChute Parachute Systems" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/RealismOverhaul/SmokeScreen_EffectCfgs/FASA.cfg
Installing Mod : RealPlume v7.0.4
Owning Mod     : RealismOverhaul
CKAN Version   : development (beta)

Your GameData has been returned to its original state.

Error!

**Comment by AlexanderDzhoganov** [comment]
Fixed in https://github.com/KSP-CKAN/CKAN/releases/tag/v1.5.4

**Comment by parsala** [comment]
thanks
