### ISSUE TITLE
packaging error

### ISSUE THREAD

**Issue by Zaran** [KSP-CKAN/CKAN-meta#234]
GameData/RealismOverhaul/SmokeScreen_EffectCfgs/FASA.cfg
Installing Mod : RealPlume v7.0.4
Owning Mod     : RealismOverhaul
CKAN Version   : v1.5.3-0-g0000000 (beta)

**Comment by AlexanderDzhoganov** [comment]
Fixed in https://github.com/KSP-CKAN/CKAN/releases/tag/v1.5.4
