### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by spikes2020** [KSP-CKAN/CKAN-meta#235]
About to remove:

Done!

About to install...

 * AJE 1.7a (cached)
 * CrossFeedEnabler v3.2 (cached)
 * DDSLoader 1.8.0.0 (cached)
 * FerramAerospaceResearch v0.14.6 (cached)
 * KerbalJointReinforcement v3.0.1 (cached)
 * ModuleManager 2.5.6 (cached)
 * ModuleRCSFX v3.4 (cached)
 * RealFuels rf-v8.3 (cached)
 * RealismOverhaul v7.0.5 (cached)
 * RealPlume v7.0.4 (cached)
 * RealSolarSystem v8.5 (cached)
 * RSSTexturesDDS8192 1.0 (cached)
 * SmokeScreen 2.5.3 (cached)
 * BetterBuoyancy v1.0 (cached)
 * ConnectedLivingSpace 1.1.0.0 (cached)
 * DeadlyReentry v6.4.0 (cached)
 * KSP-AVC 1.1.5.0 (cached)
 * MechJeb2 2.4.2 (cached)
 * ProceduralDynamics v0.9.3 (cached)
 * ProceduralFairings v3.11 (cached)
 * ProceduralParts v0.9.21 (cached)
 * RealChute 1.2.6.3 (cached)
 * RemoteTech v1.5.2 (cached)
 * TextureReplacer 2.1.2 (cached)
 * CustomBiomes-Data-RSS v8.5 (cached)
 * CustomBiomes v1.7.2 (cached)

Module "Advanced Jet Engine (AJE)" successfully installed
Module "Crossfeed Enabler" successfully installed
Module "DDSLoader" successfully installed
Module "Ferram Aerospace Research" successfully installed
Module "Kerbal Joint Reinforcement" successfully installed
Module "Module Manager" successfully installed
Module "ModuleRCSFX" successfully installed
Module "Real Fuels" successfully installed
Module "Realism Overhaul" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/RealismOverhaul/SmokeScreen_EffectCfgs/FASA.cfg
Installing Mod : RealPlume v7.0.4
Owning Mod     : RealismOverhaul
CKAN Version   : v1.5.3-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by AlexanderDzhoganov** [comment]
Fixed in https://github.com/KSP-CKAN/CKAN/releases/tag/v1.5.4
