### ISSUE TITLE
Issues installing Universal Storage KAS

### ISSUE THREAD

**Issue by RobRoseKnows** [KSP-CKAN/CKAN-meta#236]
I installed the Universal Storage module just fine but I get this error when I try to install the KAS Pack:

File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.5-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

I've already updated to the latest version. I'm not sure what's up.

**Comment by hakan42** [comment]
Well-known problem, you don't need to install the KAS anymore, universal storage does this itself via ModuleManager files.
