### ISSUE TITLE
Realism Overhaul and Universal Storage Packing issue

### ISSUE THREAD

**Issue by msholly** [KSP-CKAN/CKAN-meta#241]
File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.5-0-g0000000 (beta)

Trying to install Realism Overhaul and got this error. Need any more info?

**Comment by hakan42** [comment]
Good catch, the RealismOverhaul netkan was referencing the KAS and TAC packages directly. Removed, an updated ckan should be available within the hour.

https://github.com/KSP-CKAN/NetKAN/pull/475

**Comment by msholly** [comment]
Still encountering this issue. No rush for myself, I'll just do it manaully. But wanted to report the issue anyways. 

File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.6-0-g0000000 (beta)

Love your program!
