### ISSUE TITLE
Universal Storage Packing Issue

### ISSUE THREAD

**Issue by Goonzilla** [KSP-CKAN/CKAN-meta#242]
With Universal Storage core already installed, when trying to install the KAS addon I recieve this error.
File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.6-0-g0000000 (beta)

**Comment by hakan42** [comment]
Well-known issue, you do not need the US-KAS addon anymore. The core does everything itself via ModuleManager files.

**Comment by YellowApple** [comment]
Should UniversalStorage-KAS be removed from CKAN, then, if it's now been incorporated into UniversalStorage itself?  Was about to report the same exact issue.
