### ISSUE TITLE
Overwrite error: UniversalStorage addons

### ISSUE THREAD

**Issue by NaleshSA** [KSP-CKAN/CKAN-meta#249]
File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.6-0-g0000000 (beta)

Unable to install addon to Universal storage due to it going in the same folder.
Seems that the KAS addon has been added to the main file?
http://www.kingtiger.co.uk/kingtiger/wordpress/universal-storage-a-mod-for-kerbal-space-program/

**Comment by NaleshSA** [comment]
Checked the changelog, seems that all addons got folded into the main one indeed.

"Packs combined to a single download, Module Manager now creates parts based on other mods you have installed"
http://forum.kerbalspaceprogram.com/threads/75129-Universal-Storage-1-0-90-0-%28For-KSP-0-90%29-2nd-January-2015?p=1065785&viewfull=1#post1065785

**Comment by hakan42** [comment]
Fixed by now with the special "Deprecated" version releases of the subpackages.
