### ISSUE TITLE
Two directories with identical names but different case

### ISSUE THREAD

**Issue by SpaceTeph** [KSP-CKAN/CKAN-meta#251]
Both those directories are in the repo:

ContractConfigurator-SCANSat
ContractConfigurator-SCANsat

Works flawlessly on *NIX systems for sure, but I have the repository checked out under Windows and this wreaks havoc with git because those two are one and the same for Windows filesystems. git subsequently always tells me that ContractConfigurator-SCANSat/ContractConfigurator-SCANsat-1.0.1.ckan has been changed, regardless of what I do.

**Comment by hakan42** [comment]
Let me check what caused the second directory. It will take another hour until I can get to my desktop though.

**Comment by hakan42** [comment]
Fixed netkan file to have the correct case and removed the broken directory from CKAN-meta. The files *inside* that directory had the correct identifers, so we should not run into problems with people not being to upgrade CC-SCANsat
