### ISSUE TITLE
Universal Storage - KAS Pack Error

### ISSUE THREAD

**Issue by CAPFlyer** [KSP-CKAN/CKAN-meta#260]
When attempting to update UAS, I get an unhandled exception due to "folder not empty" error.  Uninstalling the KAS Pack resolves the problem, but attempting to re-install KAS Pack after gives the following error -

File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.6-0-g0000000 (beta)

**Comment by hakan42** [comment]
The Universal Storage addon was modified so you don't need the KAS pack anymore. It is provided by ModulManager files.
