### ISSUE TITLE
Mk3MiniExpansionPack is expanded from two netkan files

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/CKAN-meta#261]
It's pretty bizzare becouse there is one ckan file for this mod. Both entries in mods list  seems to be identical. 
I checked it out on two PCs both Windows and Linux and the problem appears but only while I'm using GUI.
 ```ckan.exe available``` gives me correct results.
(so it can be a bug in the ckan.dll)

**Comment by hakan42** [comment]
Fortunately, no bug in ckan.dll. We have two netkan files, https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Mk3MiniExpansionPack.netkan and https://github.com/KSP-CKAN/NetKAN/commits/master/NetKAN/OPTMk3MiniExpansion.netkan both expanding the same kerbalstuff archive.

Aaaaaaand another use case for deprecation addons :smiling_imp:

**Comment by hakan42** [comment]
Also, maybe we need a new quality check in the netkan build that greps kerbalstuff URLs and verifies uniqueness...

On the other hand, two netkans might install differing parts of the same addon zip, so maybe even the "install" section needs to be taken into consideration.

**Comment by Dazpoet** [comment]
This has recieved a very ugly hack to contain the issue in the above PR, closing this.
