### ISSUE TITLE
UniversalStorage-KAS

### ISSUE THREAD

**Issue by sharky98** [KSP-CKAN/CKAN-meta#264]
Hi, I just updated ckan to the latest version, and tried to add UniversalStorage-KAS to my mods. I'm getting an error each time, whatever the way I try to install it (command line, gui, with UniversalStorage selected or not manually, doing a repair, removing, clearing the cache, etc.). Here the error I got:

F:\Games\KSP\KSP-0.90>ckan install UniversalStorage-KAS
About to install...

 * UniversalStorage-KAS 1.0.0 (cached)
 * UniversalStorage 1.0.90.1 (cached)

Continue? [Y/N] y

Installing mod "UniversalStorage-KAS 1.0.0"
Installing mod "UniversalStorage 1.0.90.1"
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KAS Container.tga
Installing Mod : UniversalStorage 1.0.90.1
Owning Mod     : UniversalStorage-KAS
CKAN Version   : v1.5.6-0-g0000000 (beta)

Your GameData has been returned to its original state.

**Comment by Paul-kingtiger** [comment]
This pack is no longer required.  the Universal Storage KAS pack is now included in the Universal Storage download.  Same goes for the other add on packs.

**Comment by hakan42** [comment]
A "Deprecated" ckan version is being generated just now, which allows your installation to continue successfully.
