### ISSUE TITLE
Request to remove some mods from CKAN (no longer required as mod is discontinued)

### ISSUE THREAD

**Issue by Paul-kingtiger** [KSP-CKAN/CKAN-meta#268]
Hi, 
Can you please remove the following mods from CKAN-meta as the mod have been rolled into the UniversalStorage mod.  Users shouldn't be downloading the mods and they are no longer supported.

UniversalStorage-ECLSS
UniversalStorage-IFI
UniversalStorage-KAS
UniversalStorage-SNACKS
UniversalStorage-TAC

**Comment by hakan42** [comment]
Trouble is with the people who have those already installed. 

We should modify the netkans for the deprecated mods so they do not install any file at all but keep them in CKAN-meta for some more time until everyone has deinstalled them. 

And, enhancement request to the core here, introduce some way to alert the user that a mod is deprecated and should be deinstalled. This might take an schema update though, and testing how older client handle "unknown" tags.

**Comment by hakan42** [comment]
@Paul-kingtiger, could I ask you kindly upload one more version of each of the deprecated mods, each containing only an unique Readme file (readme-IFI, readme-KAS etc.) so we have a clean update path for people who already have installed your older packages?

**Comment by Paul-kingtiger** [comment]
@hakan42 
I have uploaded new versions of the mods to Kerbal Stuff with the file as requested.
Thanks,
Paul

**Comment by hakan42** [comment]
Thanks, I will take care of modifying the netkan files.

**Comment by hakan42** [comment]
The "Deprecated" ckan versions are being generated just now, should be available via CKAN within the hour.
