### ISSUE TITLE
UniversalStorage conflicts with UniversalStorage-KAS and cannot be installed

### ISSUE THREAD

**Issue by SteamTrout** [KSP-CKAN/CKAN-meta#269]
About to remove:

Done!

About to install...

 * UniversalStorage-KAS 1.0.0 (cached)
 * UniversalStorage 1.0.90.2 (cached)

Module "Universal Storage [KAS PACK]" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage 1.0.90.2
Owning Mod     : UniversalStorage-KAS
CKAN Version   : v1.5.6-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by hakan42** [comment]
A "Deprecated" ckan version is being generated just now, which allows your installation to continue successfully.
