### ISSUE TITLE
Installing ckan on mac - Yosemite, 10.10.1

### ISSUE THREAD

**Issue by billymat** [KSP-CKAN/CKAN-meta#275]
Hi, i have tried everything from mono to wine. When I install mono the exe won't even open but when i open wine it shows the gui but every directory for ksp is invalid. If anyone could help with my issue ut would be greatly appreciated, thanks.

**Comment by Ippo343** [comment]
Wrong section. Please open support tickets at KSP-CKAN/CKAN-support .
Also closing this, as it's very old.
