### ISSUE TITLE
Astronomer's Pack packages unavailable

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-meta#279]
Thanks for packaging Astronomer's Pack but it appears that none of the packages are available to be installed through CKAN. From a quick look it seems to be because they depend on `AstronomersPack-Clouds`, `AstrnomersPack-PlanetShine`, or `AstronomersPack-DistantObjectEnhancement` which no longer appear in the repository.

Looks like they were removed in f7371848 by @SpaceTeph, which was part of #252, it's hard to tell from the PR diff because some of the new files are so similar to the deleted files that they appear as a file move rather than a deletion and add.

**Comment by SpaceTeph** [comment]
*sigh* looks I should have done more checking in that PR. :disappointed:

I'll revert that one commit, it should do the trick.

**Comment by SpaceTeph** [comment]
PR #280 should fix it.
