### ISSUE TITLE
QuickMute Support

### ISSUE THREAD

**Issue by malahx** [KSP-CKAN/CKAN-meta#281]
Hello, I want to index my new mod on the CKAN repo ;) thanks.

QuickMute.ckan:
{
"spec_version" : 1,
"identifier" : "QuickMute",
"$kref" : "#/ckan/kerbalstuff/509",
"x_netkan_license_ok": true
"install": [
{
"file" : "GameData/QuickMute",
"install_to" : "GameData"
}
]
"suggests": [
{
"name": "Toolbar"
}
]
}

**Comment by hakan42** [comment]
Fixed by PR 580, please test
