### ISSUE TITLE
Issue with PlanetShine

### ISSUE THREAD

**Issue by autrilla** [KSP-CKAN/CKAN-meta#283]
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/PlanetShine/Config/CelestialBodies.cfg
Installing Mod : PlanetShine 0.2.2
Owning Mod     : AstronomersPack-PlanetShine
CKAN Version   : v1.5.6-0-g0000000 (beta)

**Comment by dbent** [comment]
```
Installing Mod : PlanetShine 0.2.2
Owning Mod : AstronomersPack-PlanetShine
```

You already have PlanetShine installed by virtue of installing `AstronomersPack-PlanetShine`.

**Comment by autrilla** [comment]
@dbent That is just a configuration.

**Comment by dbent** [comment]
@autrilla, `PlanetShine` is a dependency of `AstronomersPack-PlanetShine` was it not automatically installed when you installed `AstronomersPack-PlanetShine`?

**Comment by Ippo343** [comment]
This issue was moved to KSP-CKAN/CKAN-support#80
