### ISSUE TITLE
Error installing TAC-LS

### ISSUE THREAD

**Issue by reseune** [KSP-CKAN/CKAN-meta#286]
The following error is received when installing TAC-LS with TAC-LS Stock Config, or when attempting to install TAC-LS Stock Config by itself.  

Module "TAC Life Support (TACLS) - stock config" successfully installed
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
If this problem re-occurs, then it maybe a packaging bug.
Please report it at:
https://github.com/KSP-CKAN/CKAN-meta/issues/new
Please including the following information in your report:
File           : GameData/ThunderAerospace/TacLifeSupportContainers/Food.cfg
Installing Mod : TACLS v0.10.2b
Owning Mod     : TACLS-Config-Stock
CKAN Version   : v1.5.3-0-g0000000 (beta)
Your GameData has been returned to its original state.
Error!

**Comment by Ippo343** [comment]
This issue was moved to KSP-CKAN/CKAN-support#79
