### ISSUE TITLE
WaypointManager not being picked up.

### ISSUE THREAD

**Issue by jrossignol** [KSP-CKAN/CKAN-meta#306]
I have a feeling that me renaming stuff has made CKAN unhappy.  The commit for the .netkan in question is from https://github.com/KSP-CKAN/NetKAN/commit/a37bf75378441c8c9744d5f3f7895e5883a88454

**Comment by hakan42** [comment]
The root issue is the jenkins server on ci.ksp-ckan.org which failed and the MirrorKAN process which downloaded a zero-byte netkan.exe

I worked around that, and now MirrorKAN is running again, so expect your ckan within the hour.
