### ISSUE TITLE
Conflict between ODFC and SatBatts

### ISSUE THREAD

**Issue by amedee** [KSP-CKAN/CKAN-meta#307]
ODFC and SatBatts don't seem to play well together.

> Oh no! We tried to overwrite a file owned by another mod!
> Please try a `ckan update` and try again.
> 
> If this problem re-occurs, then it maybe a packaging bug.
> Please report it at:
> 
> https://github.com/KSP-CKAN/CKAN-meta/issues/new
> 
> Please including the following information in your report:
> 
> File           : GameData/Okram/Agencies/Okram.cfg
> Installing Mod : ODFC 1.0
> Owning Mod     : SatBatts
> CKAN Version   : development (beta)
> 
> Your GameData has been returned to its original state.
> 
> Error!

**Comment by Dazpoet** [comment]
Looking at the NetKAN files and this problem should no longer exist. A reinstall of the mods should resolve the issue as the shared assets have been broken into a seperate mod.
