### ISSUE TITLE
Conflicting mods caused by incorrect folder

### ISSUE THREAD

**Issue by Xarun** [KSP-CKAN/CKAN-meta#310]
As described [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-0-9-Feb-2015?p=1744694&viewfull=1#post1744694) all of my mods conflict with each other cause CKAN doesn't detect the proper folder for the mod. 
For example [here](https://github.com/KSP-CKAN/CKAN-meta/blob/master/CraftHistory/CraftHistory-1.0.1.ckan) "file" is "GameData/KerboKatz" instead of "GameData/KerboKatz/CraftHistory" and the "GameData/KerboKatz/Textures" folder doesn't get excluded, resulting in all 3 of my mods conflicting with each other for the "GameData/KerboKatz/Textures" folder.
List of the mods:
 * [ForScienceContinued!](https://github.com/KSP-CKAN/CKAN-meta/tree/master/ForScienceContinued) -> [On KS](https://kerbalstuff.com/mod/477/)
 * [CraftHistory](https://github.com/KSP-CKAN/CKAN-meta/tree/master/CraftHistory) -> [On KS](https://kerbalstuff.com/mod/598/)
 * [KerbalScienceExchange](https://github.com/KSP-CKAN/CKAN-meta/tree/master/KerbalScienceExchange) -> [On KS](https://kerbalstuff.com/mod/597/)
 * [KerboKatzUtilities](https://github.com/KSP-CKAN/CKAN-meta/tree/master/KerboKatzUtilities) -> [On KS](https://kerbalstuff.com/mod/600/)

**Comment by hakan42** [comment]
Please split the ForScienceContinued in its own ticket. Makes it much easier to process each on its own.

**Comment by AlexanderDzhoganov** [comment]
hm, have the mods been taken down from KS? I'm trying to resolve this issue.

**Comment by AlexanderDzhoganov** [comment]
Sorry for the delay, fixed in https://github.com/KSP-CKAN/NetKAN/pull/785.
