### ISSUE TITLE
Update for ForScienceContinued isn't showing up

### ISSUE THREAD

**Issue by Xarun** [KSP-CKAN/CKAN-meta#311]
ForScienceContinued got an update 4 days ago which still isn't showing up in this repo.
[ForScienceContinued!](https://github.com/KSP-CKAN/CKAN-meta/tree/master/ForScienceContinued) -> [On KS](https://kerbalstuff.com/mod/477/)

**Comment by Dazpoet** [comment]
Looks like this was resolved, closing the issue and thanks for pointing it out :)
