### ISSUE TITLE
Planet Shine is breaking stuff

### ISSUE THREAD

**Issue by masutofukuda** [KSP-CKAN/CKAN-meta#313]
Hello, there are several packages that seem to force PlanetShine to install despite deselecting it.  PlanetShine keeps conflicting with other stuff.

Copy pasta below:

About to remove:

 * PlanetShine
Removing PlanetShine...
Done!

About to install...

 * AstronomersPack Interstellar.V2 (cached)
 * RocketdyneF-1 1.2 (cached)
 * AstronomersPack-PlanetShine Interstellar.V2 (cached)
 * AstronomersPack-Clouds-High Interstellar.V2 (cached)
 * PlanetShine 0.2.2 (cached)
 * EnvironmentalVisualEnhancements 7-4 (cached)

Module "Astronomer's Visual Pack" successfully installed
Module "Rocketdyne F-1" successfully installed
Module "Astronomer's Pack - PlanetShine configuration" successfully installed
Module "Astronomer's Pack - Clouds - High" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/PlanetShine/Config/CelestialBodies.cfg
Installing Mod : PlanetShine 0.2.2
Owning Mod     : AstronomersPack-PlanetShine
CKAN Version   : development (beta)

Your GameData has been returned to its original state.

Error!

**Comment by fobok1** [comment]
I had this same problem. I got around it by uninstalling Planetshine at a separate time from installing Astronomer's Pack.

**Comment by Dazpoet** [comment]
Pretty sure this is fixed now?
