### ISSUE TITLE
WaypointManager not being picked up

### ISSUE THREAD

**Issue by jrossignol** [KSP-CKAN/CKAN-meta#315]
Looks like the bot has run since my PR (see https://github.com/KSP-CKAN/NetKAN/commit/9765ccea9bde2b4cdf962c1aaf252c63d68a580e), but it's not creating a new WaypointManager folder. :disappointed:

**Comment by hakan42** [comment]
Give it another hour for the next run,  maybe we merged the pr just at the wrong time. If it does not  work, I'll check the server first thing tomorrow morning (computer not available at the moment)

**Comment by jrossignol** [comment]
Yup, just came through - looks like I jumped the gun this time.  Thanks as always!
