### ISSUE TITLE
Conflicting Mods

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN-meta#316]
Hey Guys,

First off let me thank you from the core.  I've been hoping for something like this for a long time.  You guys rock!  Now, to get everyone else onboard.

Anywho,  I've found a problem with installing SpaceTiger's Mod.  It seems that he has both the complete mod CraftHistory and his utilities mod KerboKatzUtilities provided as separate downloads.  Unfortunately, one cannot install CraftHistory because KerboKatzUtilities is provided inside and CKAN only recognizes the other "utilities only" package as "owning" files within.

I did manage to game the install process by deleting the offending file from CraftHistory. <grin>

scott@Jupiter:~$ mono ~/Games/KSP_Active/ckan.exe install CraftHistory
About to install...

 * CraftHistory 1.1.1 (cached)
 * KerboKatzUtilities 1.0.2 (cached)

Continue? [Y/N] y

Installing mod "CraftHistory 1.1.1"
Installing mod "KerboKatzUtilities 1.0.2"
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/KerboKatz/Textures/tooltipBG.png
Installing Mod : KerboKatzUtilities 1.0.2
Owning Mod     : CraftHistory
CKAN Version   : v1.6.0-0-g0000000 (beta)

Your GameData has been returned to its original state.

**Comment by Xarun** [comment]
already reported this issue see #310 :)

**Comment by AlexanderDzhoganov** [comment]
This is now fixed.
