### ISSUE TITLE
mod overwrite error

### ISSUE THREAD

**Issue by adalast** [KSP-CKAN/CKAN-meta#323]
File           : GameData/KerboKatz/Textures/tooltipBG.png
Installing Mod : KerboKatzUtilities 1.0.3
Owning Mod     : KerbalScienceExchange
CKAN Version   : v1.5.6-0-g0000000 (beta)

**Comment by Xarun** [comment]
already reported: see #310 and #316

**Comment by AlexanderDzhoganov** [comment]
This is now fixed.
