### ISSUE TITLE
File duplication between Orbital Material Science and NehemiahScienceCommon

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/CKAN-meta#327]
These mods include many of the same files, and CKAN complains, like so:

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/NehemiahInc/NE_Science_Common/Agencies/Agents.cfg
Installing Mod : NehemiahScienceCommon 1.0
Owning Mod     : OrbitalMaterialScience
CKAN Version   : v1.6.5-0-g0000000 (beta)

Your GameData has been returned to its original state.

**Comment by Dazpoet** [comment]
I'm unable to reproduce this behaviour, does it still persist? The files where updated some 5-7 days ago it seems to have been resolved then.

**Comment by damerell** [comment]
On Wednesday, 18 Mar 2015, Willhelm Rendahl wrote:
>I'm unable to reproduce this behaviour, does it still persist? The files where
>updated some 5-7 days ago it seems to have been resolved then.

I can't now reproduce it. Thanks.

-- 
David Damerell <damerell@chiark.greenend.org.uk>
And now, a seemingly inexplicable shot of a passing train.
Today is First Chedday, March - a public holiday.
Tomorrow will be First Stilday, March - a weekend.
