### ISSUE TITLE
adding request: XT Landertron

### ISSUE THREAD

**Issue by abenkovskii** [KSP-CKAN/CKAN-meta#338]
I like this mod. It helps landing probes with RemoteTech signal delay.
http://forum.kerbalspaceprogram.com/threads/61294-0-90-XT-Landertron-Smart-Retrorockets-for-Landers-and-Spaceplanes-v0-08-Oct-10

**Comment by Dazpoet** [comment]
Since this is hosted on mediafire we are unable to index it on CKAN. Looks like an awesome mod though O_o

Closing this since there's nothing we can do.
