### ISSUE TITLE
update KerbalFoundries to latest available version

### ISSUE THREAD

**Issue by JustinKerbice** [KSP-CKAN/CKAN-meta#340]
current CKAN meta is: KerbalFoundries-Alpha_1.7c.ckan, with "version": "Alpha_1.7c" data

on KS, KF mod is 1.8g (2015-03-06)

**Comment by hakan42** [comment]
Version strings are compared alphabetically, thus "1.8g" comes earlier than "Alpha_1.7c"

**Comment by TeddyDD** [comment]
Should we use epoch then?

**Comment by Dazpoet** [comment]
This issue is resolved for now. beta_1.8g shows up in CKAN. This will be a headache if KF ever changes over to only numbers, which would normally be the prefered way. However that's a problem for future us, current us have no problems.

Issue is resolved so I'm closing this.
