### ISSUE TITLE
I can not install B9 R5.2.8

### ISSUE THREAD

**Issue by www2000** [KSP-CKAN/CKAN-meta#355]
Hi i wand install B9 but i get this error:

[code]
Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install B9 R5.2.8 via the CKAN,
then please manually uninstall the mod which owns:

Ships/SPH/B9 BRV-4 Heinlein.craft

and try again.

Your GameData has been returned to its original state.

Error!
[/code]

**Comment by Dazpoet** [comment]
If you manuelly remove or rename the file outlined in the message it should work to install B9. Have you had it installed earlier and perchance forgot to remove the .craft files?
