### ISSUE TITLE
Package load error

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN-meta#356]
About to remove:

Done!

About to install...

 * KerbalAircraftExpansion v2.3.4 (cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/Firespitter/Resources/Firespitter.cfg
Installing Mod : KerbalAircraftExpansion v2.3.4
Owning Mod     : Firespitter
CKAN Version   : v1.6.6-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by TeddyDD** [comment]
Hey @Bit-Fiddler 
I'm last one who was messing with KAX metadata so I would like to fix this however I can't recreate this error. For me it works 
```
KerbalAircraftExpansion
About to install...

 * KerbalAircraftExpansion v2.3.4
 * FirespitterCore 7.0.5463.30802

Continue? [Y/N] y

Downloading "https://kerbalstuff.com/mod/391/Kerbal Aircraft Expansion (KAX)/download/v2.3.4"
Downloading "http://firespitter.s3.amazonaws.com/FirespitterCore-7.0.5463.30802.zip"
0 kbps - downloading - 15 MiB left - 1%           
Installing mod "KerbalAircraftExpansion v2.3.4"
Installing mod "FirespitterCore 7.0.5463.30802"
Updating registry
Commiting filesystem changes
Rescanning GameData
Done!
```
I suppose you have Firespitter.cfg file created by some other mod.
Could you post here content of Firespitter/Resources/Firespitter.cfg file here? And your mod list if it's not a problem.
KAX provides this file with following resource definition 
```
RESOURCE_DEFINITION
{
  name = FSCoolant
  density = 0.005
  flowMode = ALL_VESSEL
  transfer = PUMP
}
```

**Comment by jazzkutya** [comment]
Hi, I have the same problem.
I think the "conflicting" mod is firespitter itself. How can we install both firespitter (full) and KAX?
Shouldn't you remove firespitter-core from your mod and just add a dependency?

**Comment by jazzkutya** [comment]
i see the firespitter-core dependency is there

**Comment by jazzkutya** [comment]
Also it seems kax is not your mod, so I'm sorry for my incorrect wording above.

**Comment by Bit-Fiddler** [comment]
Sorry Teddy.  did not realize these were 2 way discussions...  I though they were just a report a problem sort of thing.

But yes I still have the issue and sent another report along with JSI/RPM...   any way the JSI issue is resolved but I still can't get KAX to install

**Comment by TeddyDD** [comment]
@Bit-Fiddler https://github.com/KSP-CKAN/NetKAN/pull/1264 This should repair KAX take a look.

**Comment by mgsdk** [comment]
Closed via https://github.com/KSP-CKAN/NetKAN/pull/1264.
