### ISSUE TITLE
Doubts about Infernal robotix model rework

### ISSUE THREAD

**Issue by cid0rz** [KSP-CKAN/CKAN-meta#370]
Dear all, first of all sorry to bother you. I'd like to install via ckan the infernal robotics model rework. i know maybe nobody put it on ckan so i should include it if i like. When i go to the kerbal stuff page of the mod
https://kerbalstuff.com/mod/675/Infernal%20Robotics%20Model%20Rework%20-%20Core%20Pack
ckan appears in a globe near the mod, so... i thought maybe it is already done but I can't see it. it seems that ckan updates repositories correctly and I have the updated version 1.6.9. 
I'd try to add it to ckan but i'm afraid not being enogh skillfull for that and my kwnoledge of this mods is not too deep.

Can anybody help me? Thank you guys

**Comment by TeddyDD** [comment]
Hello @cid0rz 
From what I can see Infernal robotix metadata is still work in progress but I think it will be available soon. You can track progress here KSP-CKAN/NetKAN#951. Wait until this will be merged :)

**Comment by Dazpoet** [comment]
From what I gather the model rework depends on the IR rework and the latter has had a release yet (just pre-releases). Might be able to resolve the issue by handpackaging a pre-release directly into CKAN-meta though.

**Comment by cid0rz** [comment]
Thank you guys, i will try the manual solution for now ^^ you were fast and helpful! I'm sad marce is leaving like that... :( thx again!

**Comment by cid0rz** [comment]
Infernal robotics was updated to .20 so some progress but the aditional parts are not showing :( I see them in the recommended metadata but they are grey and no prompt to install :S

**Comment by Dazpoet** [comment]
Wait what, updated to 0.20 in CKAN? How are you getting that? My version shows 0.19.3 as latest version and the NetKAN update that will allow the install of the Model Rework is not yet merged so that would be why you can't see it. I'm awaiting some review and ok'ing before I can merge them.

**Comment by cid0rz** [comment]
I tried installing from a .ckan with the text you posted, then a box in the column update for IR appeared

the text was:

{
    "spec_version": "v1.4",
    "identifier": "InfernalRobotics",
    "license": "GPL-3.0",
    "release_status": "stable",
    "resources": {
        "repository": "https://github.com/MagicSmokeIndustries/InfernalRobotics",
        "homepage": "http://forum.kerbalspaceprogram.com/threads/114014"
    },
	"recommends"	: [ { "name" : "IR-Model-Rework-Core" },
						{ "name" : "IR-Model-Rework-Expansion" },
						{ "name" : "IR-Model-Rework-Utility" },
						{ "name" : "TweakScale" } ],
	"install"		: [ { "find" : "MagicSmokeIndustries",
						"install_to" : "GameData" } ],
    "ksp_version": "0.90",
    "name": "Magic Smoke Industries Infernal Robotics",
    "abstract": "Making stuff move",
    "author": [ "erendrake", "pellinor0", "ZodiusInfuser", "sirkut", "Ziw" ],
    "version": "0.20c",
    "download": "https://github.com/MagicSmokeIndustries/InfernalRobotics/releases/download/v0.20C/IR.Rework.P3.zip"
}
I clicked and updated ^^

**Comment by Dazpoet** [comment]
FYI that update is savebreaking. I changed the PR to be 0.19.4 instead after some discussion with one of the mod authors telling me the first officiall release will probably be 0.20 and your version of the file might be considered "higher" than that.

The reason you're not seeing the model rework stuff is that it hasn't been added to repositories yet.

**Comment by cid0rz** [comment]
I removed it and re-installed, no save file damage as far as I can see. i had only 1 ship with IR components and seems to work as before. Thx for everything i will wait for the official updates. :E I hope nothing will get broken for this. Thx for the support and the knowledge
