### ISSUE TITLE
Kopernicus needs an update

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-meta#402]
See [here](http://forum.kerbalspaceprogram.com/threads/114649-0-90-Kopernicus-Pre-Alpha-%280-0-6%29?p=1868936&viewfull=1#post1868936)

I'm guessing we'll see a new version soon'ish.

**Comment by Acecool** [comment]
From what I'm seeing, each directory contains a ckan file; I'm surprised if they aren't automatically generated... If they aren't then there needs to be an update to CKAN which handles automatic updates using a list of resources such as Github, Bitbucket, KSP Forum, etc... Managing all of that data manually would take too much time to keep up to date all the time...

**Comment by Dazpoet** [comment]
Most of our mods are generated from .netkan files over in the NetKAN repository. However some, like this one, don't have a release flow we can tap into using those so we're stuck manually updating.

**Comment by NathanKell** [comment]
Kopernicus does have github releases. https://github.com/BryceSchroeder/Kopernicus/releases

**Comment by Dazpoet** [comment]
Yes but we can't index pre-releases :/

**Comment by NathanKell** [comment]
Oh. Let me fix that. :)

**Comment by NathanKell** [comment]
Done for 0.0.7. I can do the earlier ones too if you want.

**Comment by Dazpoet** [comment]
Nah 0.0.7 is good enough for me :D

**Comment by dbent** [comment]
I'm assuming this is can be closed now. Re-open if I'm wrong.
