### ISSUE TITLE
Contract Configurator 1.0.0 isn't being picked up

### ISSUE THREAD

**Issue by jrossignol** [KSP-CKAN/CKAN-meta#413]
The newest [Contract Configurator](https://github.com/jrossignol/ContractConfigurator/releases/tag/1.0.0) hasn't been picked up (released ~10 hours ago).  A few of the mods that depend on it have been picked up.  Netkan file hasn't changed, and I did a quick JSON validation of the .version file in the zip file.

Is there an easy to access place that I can see the result of the netkan bot attempting to build stuff so I can self-diagnose this stuff more easily?  I poked around jenkins, but only saw stuff related to PRs.

**Comment by Dazpoet** [comment]
Our bot took a nap but everything is running along smoothly again now.

It was a totally unrelated .netkan file ruining the fun for everyone.
