### ISSUE TITLE
Tac - Life Support Error when installing.

### ISSUE THREAD

**Issue by Moonratt** [KSP-CKAN/CKAN-meta#425]
GameData/ThunderAerospace/TacLifeSupportContainers/Food.cfg
Installing Mod : TACLS-Config-Stock v0.11.1
Owning Mod     : TACLS
CKAN Version   : v1.5.3-0-g0000000 (beta)

**Comment by Dazpoet** [comment]
first of all I recommend updating to the [latest version of CKAN](https://github.com/KSP-CKAN/CKAN/releases).

Then onto the issue, are you able to reproduce this problem on an empty install? What steps lead to this happening? What other mods do you have installed? Does it happen through GUI or Commandline client?

Looking at the metadata files TACLS-Config-Stock v0.11.1 only installs a single file and it's not the one specified here. That does however not mean that it acctually works perfectly either hence my asking if it's reproducable.

**Comment by Moonratt** [comment]
Bah, upgrading CKAN solved the issue with the TAC install. Should have
considered that given the new Kerbal release.

I'm going to test a couple of the other similar issues I had but I suspect
that using the new client will have cleaned up the problem.

Thanks for the response.

Dave

**Comment by Dazpoet** [comment]
If your issues are with mods like Astronomers, TACLS and similar mods with configs seperated you might want to take a look at https://github.com/KSP-CKAN/CKAN-GUI/issues/95, If you run into that kind of issue please do report back so we can track it all down.

**Comment by Dazpoet** [comment]
Seems this has been resolved so I'm closing it :)
