### ISSUE TITLE
Wrong installation folder for KerbalScienceExchange

### ISSUE THREAD

**Issue by Xarun** [KSP-CKAN/CKAN-meta#450]
It was brought to my attention that [KerbalScienceExchange](https://github.com/KSP-CKAN/CKAN-meta/tree/master/KerbalScienceExchange) didn't work after installing it with CKAN. After some investigations look for the error on my part i found out its just a tiny little mistake on sides of ckan. Its puting the KerbalScienceExchange folder into the GameData folder instead of GameData/KerboKatz like it should be.

**Comment by Dazpoet** [comment]
Fixed
