### ISSUE TITLE
InfernalRobotics 0.21.2

### ISSUE THREAD

**Issue by sergioberg** [KSP-CKAN/CKAN-meta#466]
https://github.com/KSP-CKAN/CKAN-meta/tree/master/InfernalRobotics
0.21.2 is absent in CKAN app. Only 0.21. Something wrong.

**Comment by sergioberg** [comment]
May be CKAN thinks: "v0.21" > "0.21.2"

**Comment by BlackSoldierB** [comment]
Duplicate of https://github.com/KSP-CKAN/CKAN-support/issues/133?
