### ISSUE TITLE
Atomic Age links to wrong thread

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/CKAN-meta#471]
The Atomic Age mod links to http://forum.kerbalspaceprogram.com/threads/100932, but what is wanted is http://forum.kerbalspaceprogram.com/threads/104855.

**Comment by damerell** [comment]
Ferram Aerospace Research, also - omits the "forum" from the thread URL.

**Comment by Dazpoet** [comment]
Thanks, Will have someone look into this :)

**Comment by dbent** [comment]
The `AtomicAge` issue was fixed in KSP-CKAN/NetKAN#1268. the `FerramAerospaceResearch` issue is because the Kerbal Stuff metadta is wrong. I've made a [post](http://forum.kerbalspaceprogram.com/threads/20451?p=1944851#post1944851) about the issue.

**Comment by dbent** [comment]
ferram updated the Kerbal Stuff link and the `FerramAerospaceResearch` issue has been resolved with 2604186c4576117a0d7f54243b4a85a87ba94b09.

This can be closed now.

**Comment by Dazpoet** [comment]
Awesome!
