### ISSUE TITLE
Error whilst installing KAX (Kerbal Aircraft Expansion) with Firespitter present.

### ISSUE THREAD

**Issue by Poodmund** [KSP-CKAN/CKAN-meta#472]
File           : GameData/Firespitter/Resources/Firespitter.cfg
Installing Mod : KerbalAircraftExpansion v2.4.1
Owning Mod     : Firespitter
CKAN Version   : v1.6.13-0-g0000000 (beta)

With Firespitter already installed (and vice versa), KAX fails to install due to the Firespitter.cfg already being present and controlled by the other mod install.

EDIT: KSP v1.0.2

**Comment by Dazpoet** [comment]
See also https://github.com/KSP-CKAN/CKAN-meta/issues/356 and nothing @TeddyDD who seems to have self assigned to this specific problem.

**Comment by TeddyDD** [comment]
Damn it, again this. Ok, let's see...

**Comment by mgsdk** [comment]
Closed via https://github.com/KSP-CKAN/NetKAN/pull/1264.
