### ISSUE TITLE
Installing Mod : IR-Model-Rework-Expansion v01b

### ISSUE THREAD

**Issue by lilfunnyman** [KSP-CKAN/CKAN-meta#478]
Please including the following information in your report:

File           : GameData/MagicSmokeIndustries/Parts/Rework_License.txt
Installing Mod : IR-Model-Rework-Expansion v01b
Owning Mod     : IR-Model-Rework-Core
CKAN Version   : v1.5.3-0-g0000000 (beta)

**Comment by Dazpoet** [comment]
That is indeed weird because the metadata file is filtering that .txt. What mods where you installing when this happened?

If there is no specific reason for using usch an old version pf CKAN I also recommend an update.

**Comment by lilfunnyman** [comment]
I am sorry. It was actually my fault. Updated and worked fine. Sorry about that.

On May 10, 2015, at 10:02 PM, Willhelm Rendahl <notifications@github.com> wrote:

That is indeed weird because the metadata file is filtering that .txt. What mods where you installing when this happened?

If there is no specific reason for using usch an old version pf CKAN I also recommend an update.

**Comment by mgsdk** [comment]
Good to know that the updated client solved your issues. Closing this for now.
