### ISSUE TITLE
error when installing firespitter

### ISSUE THREAD

**Issue by Lazersgm** [KSP-CKAN/CKAN-meta#489]
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/Firespitter/Resources/Firespitter.cfg
Installing Mod : Firespitter v7.1.1
Owning Mod     : KerbalAircraftExpansion
CKAN Version   : v1.6.16-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Dazpoet** [comment]
This should be resolved now, no other issues about the same thing have reported otherways so I'm closing this. Please comment if the situation is not resolved so I can re-open and have another look at it.
