### ISSUE TITLE
KerbalAircraftExpansion v2.5 installation buggy

### ISSUE THREAD

**Issue by Prismatech** [KSP-CKAN/CKAN-meta#492]
* KerbalAircraftExpansion v2.5 (cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/Firespitter/Resources/Firespitter.cfg
Installing Mod : KerbalAircraftExpansion v2.5
Owning Mod     : Firespitter
CKAN Version   : v1.6.16-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by mgsdk** [comment]
Might be related to #472.

**Comment by plague006** [comment]
With KSP-CKAN/NetKAN#1264 complete it would be nice to know if this issue persists.

**Comment by Dazpoet** [comment]
An issue whos number I forgot reported this as fixed so I'm closing this for now, if issue does persist please comment so we can re-open.
