### ISSUE TITLE
HotRockets community config

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN-meta#5]
The [hotrockets thread](http://forum.kerbalspaceprogram.com/threads/65754-HotRockets!-Particle-FX-Replacement-Tutorial) has mention of a community config pack.

We index HotRockets, but not the community config. We should.

**Comment by hakan42** [comment]
The files are not only on mediafire (as linked in the forum) but on curseforge as well: http://kerbal.curseforge.com/ksp-mods/220207-hotrockets-particle-fx-replacement/files
