### ISSUE TITLE
Mod conflict KAX and FireSpitter.

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN-meta#500]
About to remove:

Done!

About to install...

 * KerbalAircraftExpansion v2.5.1
 * KerbalConstructionTime 1.1.7

Downloading "https://kerbalstuff.com/mod/391/Kerbal Aircraft Expansion (KAX)/download/v2.5.1" (libcurl)
Downloading "https://kerbalstuff.com/mod/125/Kerbal Construction Time/download/1.1.7" (libcurl)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/Firespitter/Resources/Firespitter.cfg
Installing Mod : KerbalAircraftExpansion v2.5.1
Owning Mod     : Firespitter
CKAN Version   : v1.6.16-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by plague006** [comment]
I see 2 ways to address this. Either change the depend of https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KerbalAircraftExpansion.netkan to "Firespitter" and get the full install. Or change the install stanza of https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/FirespitterCore.netkan to install "Firespitter/Resources/Firespitter.cfg".

In the case of the former, the netkan was changed specifically to not install full "Firespitter" see: e16d4507cf3875bf19a16e0d9aab1af6a8efe221 (hope that links the way I think it should).

I would think changing KAX' netkan (depends and install) would leave less room for possible future conflicts.

**Comment by plague006** [comment]
This also relates back to #472, letting better hands than mine deal with it.

**Comment by plague006** [comment]
With KSP-CKAN/NetKAN#1264 complete it would be nice to know if this issue persists.

**Comment by Dazpoet** [comment]
Should be resolved, please re-open if that is not the case.
