### ISSUE TITLE
Near Future Props links to wrong thread

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/CKAN-meta#508]
It links to the KSP forum thread for Stockalike Station Parts.

**Comment by Dazpoet** [comment]
Where should it point instead? I thought Props was a subpart of Stockalike Station Parts?

**Comment by damerell** [comment]
That hadn't occurred to me, I admit. I suggest http://forum.kerbalspaceprogram.com/threads/52042-0-21 - Near Future Spacecraft also depends on it, and it makes it more obvious it's a sub-mod.
