### ISSUE TITLE
Adding a new mod - OpenTree

### ISSUE THREAD

**Issue by lukeklemens** [KSP-CKAN/CKAN-meta#529]
Hello, I recently submitted my new mod netkan file via a pull request. I was unable to test the netkan file fully due to a missing dll error when generating the metadata using netkan.exe. Please let me know if there are any issues. On another note, I have made two versions of the mod - one that is compatible with mods including new parts, and another for all other users. Is there any way I can alert users to this inside your system? I have two separate files available for download through Kerbal Stuff. Any suggestions would be appreciated. Thanks. Luke

**Comment by Dazpoet** [comment]
Is this the PR you reference https://github.com/KSP-CKAN/NetKAN/pull/1377 ?

We have some discussion in there about how to solve the multiple versions from the same download.

**Comment by lukeklemens** [comment]
Yep that's the one, thanks.
