### ISSUE TITLE
Correct links for some KSP 0.90 compatibe mods. (Yes, many with large modlists and huge saves still rock 0.90)

### ISSUE THREAD

**Issue by Shaggygoblin** [KSP-CKAN/CKAN-meta#537]
I run 100+ mods on a 0.90 install.  Until ~12 of them are updated, 0.90 it is!

B9 Aerospace Pack 5.2.8 needs RasterPropMonitor Core.  downloading the 5.2.8 from the B9 thread, the .zip contains RPM.  As B9 'depends' on RPM, the install fails due to invalid RPM links.
This is the response from the RPM Author: https://github.com/Mihara/RasterPropMonitor/issues/228#issuecomment-105020775
This is the location of the 0.90 build(s) that should be used: https://github.com/Mihara/RasterPropMonitor/releases/tag/v0.19 (Both .zip at this location have version files stating 0.90.  Assuming one is RPM and one is RPM Core)

TAC Fuel Balancer once showed in CKAN as 0.90 compatible.
It is no longer listed.
This is the post where the author announced the 0.90 build, which does work : http://forum.kerbalspaceprogram.com/threads/25823-1-0-2-TAC-Fuel-Balancer-v2-5-1-2May?p=1601786&viewfull=1#post1601786
The location of the correct and working 0.90 build: https://www.dropbox.com/sh/3emtoeyky6c3w8v/AACxWYWFY-fHChhBVMOXqUMHa/TacFuelBalancer_2.4.1.1008.zip?dl=0

Bargain Rocket Parts fails download.
CKAN Link: http://ksp.gurkensalat.com/archive/BargainRockets_1.1.2.zip (Invalid)
Current, working 0.90 link: https://www.dropbox.com/sh/1fsuzvl35s2gppt/AACl7hgDMeTqYMEronUxA_yDa/BargainRockets_1.1.2.zip?dl=0

SoundingRockets! fails download.  Manually following the link CKAN uses nets a DropBox 404.
correct 0.90 compatible build: https://github.com/BobPalmer/SoundingRockets/releases/download/0.1.1/SoundingRockets_0.1.1.zip

Coherent Contracts was marked for 0.25, but remained working as intended through 0.90.
It is no longer showing as compatible in CKAN.  CKAN shows the most recent 1.02.
This is the location of the 0.90 compatible build: https://kerbalstuff.com/mod/333/Coherent%20Contracts/download/1.01 (KSP 0.25, works in 0.90)

More to follow...

**Comment by mgsdk** [comment]
#534 should fix at least the RasterPropMonitorCore issue (Got merged shortly after you reported it to IRC).

**Comment by Shaggygoblin** [comment]
I been digging almost the entire time since...
> [06:20] <Shaggygoblin> oh, real quick, the issue should be raised on CKAN or CKAN-Meta (on the NetKan)?
[06:21] <RichardLake> CKAN
[06:22] <Shaggygoblin> will do, cheers! >

 trying to locate and multi-source-verify those links before committing them here... time for me to take a coffee break...lol!  Then I get to start 'retrieving' CommSats, Orbital-Labs, Interplanetary Ferries... yay (sadface)

**Comment by Dazpoet** [comment]
What version of TAC-FB is the 0.90 recompile? We have 2.4.1, 2.5 and 2.5.1 indexed. If the recompile was never officially released then that's a pain. Might be able to index it as something like 2.4.1.1 ?

**Comment by Shaggygoblin** [comment]
v2.4.1.1008
`{
  "NAME": "TAC Fuel Balancer",
  "URL": "http://ksp-avc.cybutek.net/version.php?id=20",
  "DOWNLOAD": "",
  "VERSION": "2.4.1.1008",
  "KSP_VERSION": {
    "MAJOR": 0,
    "MINOR": 90,
    "PATCH": 0
  }
}
`

**Comment by Dazpoet** [comment]
Ok I think we got all of them now? If so this can be closed :)

**Comment by Shaggygoblin** [comment]
indeed, close it.  Unless you all prefer otherwise, I will post any more 0.90 issues like these here, to this issue, to keep them all together?  less clutter than multiple new issues regarding broken links against 0.90.  Either way, fantastic work!
