### ISSUE TITLE
Incorrect KSPAPIExtensions KSP version compatibility

### ISSUE THREAD

**Issue by darchambault** [KSP-CKAN/CKAN-meta#555]
It would seem that a NetKAN merge reverted the "ksp_version" requirement for KSPAPIExtensions from "1.0.2" to "0.90", making many mods that depend on KSPAPIExtensions impossible to install on 1.0.2 (Astronomer's Visual Pack being one of those).

**Comment by Dazpoet** [comment]
Hm, which part of AVP is now impossible to install? I just browsed through a bunch and can't seem to find the error. What does the error say?

**Comment by Dazpoet** [comment]
Is this the lucidity I spoke to on irc?

**Comment by darchambault** [comment]
It is!

Turns out the problem was unrelated to AVP. I realized I got the error for every mod I was trying to install. I removed KAE (which I had installed manually through CKAN last week), and it fixed the situation.
