### ISSUE TITLE
NetKarmgeddon - Massive Purge of CKAN metadata and scripts

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-meta#558]
More info in KSP-CKAN/CKAN#979.

**Comment by dbent** [comment]
FYI, the first commit of the purge is bb5480d18d47dc34b041fbfc732413a5b3e466b1, basically going in alphabetical order of the file names.

**Comment by Dazpoet** [comment]
Closing this in favour of the issue linked above
