### ISSUE TITLE
Add ability to enable StockPlus fixes for Claw's bugfix mod

### ISSUE THREAD

**Issue by Net-burst** [KSP-CKAN/CKAN-meta#572]
http://forum.kerbalspaceprogram.com/threads/97285

In recent version StockPlus features were implemented. To enable them you need to place config file in GameData root.

**Comment by Dazpoet** [comment]
D'oh the dl locations for this file are directly to a .cfg file and not to a .zip

**Comment by Net-burst** [comment]
CKAN can only process files inside zip? Maybe ask Claw to include file inside main archive?

**Comment by Dazpoet** [comment]
Opened https://github.com/ClawKSP/KSP-Stock-Bug-Fix-Modules/issues/2 for contact with the author

**Comment by ClawKSP** [comment]
I've added a zip file that contains the StockPlusController.cfg file to the current release.

**Comment by Net-burst** [comment]
Thanks!

**Comment by dbent** [comment]
`.netkan` created in KSP-CKAN/NetKAN#1514. @ClawKSP in the forum post you say:

> ModuleGimbalFix has StockPlus selectively disabled. If you want to enable it, you must edit the ModuleGimbalFix.cfg.

Looking at [`ModuleGimbalFix.cfg`](https://github.com/ClawKSP/KSP-Stock-Bug-Fix-Modules/blob/a637d8e7d927f7ce0b1094a15e68830db35ff28f/GameData/StockBugFixModules/ModuleGimbalFix/ModuleGimbalFix.cfg) in the repository it has `plusEnabled = False`, but in the download of `v1.0.2d.4` it has `plusEnabled = True`. Is that just something you forgot to edit out in the forum post?

Also, any better abstract than "Enhancements of stock functionality"?

**Comment by Dazpoet** [comment]
StockPlus should show up in CKAN now.

**Comment by ClawKSP** [comment]
@dbent That's actually an error in the download (because it's on in my setup for testing). Which is unfortunate, because it'll probably stir up confusion again.

Thanks for pointing it out. I suppose v1.0.2d.5 will be along in the not too distant future.

**Comment by dbent** [comment]
Closing this as implemented.
