### ISSUE TITLE
Issues with manual mod versioning

### ISSUE THREAD

**Issue by SkyMarshal** [KSP-CKAN/CKAN-meta#577]
Just took me two hours tracking down a stupid issue that arose from people changing the download link without bumping the version number.  sarbian/ModularFlightIntegrator#3 for reference.  The offending file is [ModularFlightIntegrator-1.0.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/ModularFlightIntegrator/ModularFlightIntegrator-1.0.ckan)  I don't know your policy on dealing with this type of thing, but I'd like to make sure people don't get bit by this as well.

**Comment by SkyMarshal** [comment]
The MD5 hash for the most recently available build is `691E2453800BB15DB4FF2977547B971F` while the version I have (both installed and in CKAN's cache) is `CC14842C90223E51F149148792035150`.

**Comment by Dazpoet** [comment]
The above PR should resolve this by offering an upgrade path for those stuck on an older version

**Comment by SkyMarshal** [comment]
Works for me.
