### ISSUE TITLE
"PlanetPack" Clean-Up

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-meta#588]
There are quite a [few mods](https://github.com/KSP-CKAN/CKAN-meta/search?utf8=%E2%9C%93&q=PlanetPack) that `provide` `PlanetPack` and `conflict` with it. It seems the idea here is that all mods which provide extra planets are inherently in conflict, so a user can only select one. As far as I know, this isn't true, especially with everything moving over to `Kopernicus`. Multiple "planet packs" should be able to be safely installed so long as they don't alter the same bodies.

I propose the following:

1. Remove all `PlanetPack` `provides` and `conflicts` (nothing `depends` on `PlanetPack`).
2. Make sure all mods which extend the planet system have appropriate `conflicts` with each other (i.e. `Kopernicus`, `KopernicusTech`, `KittopiaTech`, `Kittopia`, any others?).
3. To best of our ability determine any actual conflicts that exist between planet mods.
4. Keep a look out for any conflicts that do arise and update accordingly.

----

### Progress (KSP 1.0.5):
**Files to add:**
- [x] AlternisRealSolarSystem - `Requires RSS`
- [x] BilliardsPlanetPack - `Conflicts with all packs`
- [ ] TheBorisSystem
- [ ] TheGliese-581StarSystem - `Requires LibraCORE`
- [ ] ChaniPlanetPack
- [ ] JungisPlanetPack
- [ ] KerbalBinary - `Conflicts with all packs`
- [ ] KerbalGalaxy2 - `Conflicts with all packs`
- [x] KittopiaTech - `No planet pack, requires Kopernicus`
- [x] KPlus - `Conflicts with KerbolPlus`
- [ ] LibraCORE
- [x] OtherWorlds
- [ ] RSSExpanded - `Requires RSS`
- [x] SaruPlanetPack
- [ ] SylandrosPlanetWarehouse
- [ ] TransKeptunian
- [x] UnchartedLands
- [x] WinterKerbol - `Conflicts with SigmaJoolRecolor`

**Files to update:**
- [x] AlternisKerbolRekerjiggered - `Conflicts with all packs`
- [ ] Arkas
- [x] Asclepius
- [ ] KerbolPlus (KerbalOrigins) - `Conflicts with KPlus`
- [x] Kopernicus - `No planet pack`
- [ ] KopernicusExpansion - `No planet pack`
- [ ] Kronkus
- [ ] Ktolemy - `Conflicts with all packs`
- [x] LittleGreenMenFromMars - `Requires RSS`
- [ ] NebiaAndShomma (Keridani)
- [x] NewHorizons
- [x] OuterPlanetsMod
- [x] RealSolarSystem - `Conflicts with all packs, except GalacticNeigboorhood and RSSExpanded`
- [ ] RhatssPlanetPack
- [ ] SentarExpansion
- [ ] SidosUraniaSystem
- [x] SigmaBinary-core - `No planet pack`
- [x] SigmaOPMExpansion (Sigma: OPM Tilt) - `No planet pack, Requires OPM`
- [x] SigmaOPMRecolor - `No planet pack, Requires OPM`
- [x] SigmaPluronKhato
- [x] SigmaStockRecolor (Sigma: Eve Recolor)
- [x] SigmaJoolRecolor
- [x] SmallSolarSystem - `Requires RSS-Textures`
- [x] ToySolarSystem - `Conflicts with all packs`

**Waiting for (stable) release:** 
- [ ] AstrosKopernicusPlanets
- [ ] GalacticNeighborhood - `No planet pack, it supports them`
- [ ] Kemesis
- [ ] KerbalDreams
- [ ] KerbalOuterBodiesExpansion
- [ ] KerbolStarSystems
- [ ] SigmaDimensions - `Rescale pack`
- [ ] TheSonneSystem - `Requires LibraCORE`

**Outdated packs:** - `Conflicts with Kopernicus`
- [x] DunaPlus
- [x] EvePlus
- [x] ForgottenWorlds
- [x] Insystem
- [x] InterstellarAdventure
- [x] KiriusPlanetPack
- [x] TerrestrialPlanetPack

**Comment by Dazpoet** [comment]
This was something of a hotfix to push multiple planet adding mods through the gates at once and me not being involved enough in the planetscene to acctually be able to untangle what conflicted with what. I wholeheartedly support a cleanup and defer to whoever has the patience to fix these things.

**Comment by Olympic1** [comment]
I'm actively involved in the planets packs, because I have a wiki about them, so I'll see what I can do

**Comment by Olympic1** [comment]
Some questions:
* May I delete `.netkan` / `.ckan` files from mods that aren't maintained anymore?
* Do I need to add `"provides": [ "PlanetPack" ]` in the files or not?
* Are there any specifics needed in the planet pack files?

**Comment by plague006** [comment]
Not maintained/updated, no don't delete. If they're not available (ie. error 404) then yes you can delete. As for `planetpack` I think we want to remove that as a `provide` and `conflict` entirely and instead use `conflicts` in cases where they are confirmed.

**Comment by Olympic1** [comment]
### Progress:
**Files to add:**
* [ ] AlternisKerbolReloaded
* [ ] TheBorisSystem
* [ ] ChaniPlanetPack
* [ ] KerbalGalaxy2
* [ ] Kerbol3.7
* [ ] KittopiaTech (the new one)
* [ ] Kopernicus-Config-Default
* [ ] OtherWorlds
* [ ] PlockPlus
* [ ] ResearchBodies
* [ ] RSSExpanded
* [ ] StockalikeGasPlanet2
* [ ] Trans-Keptunian

**Files to update:**
* [ ] Asclepius
* [ ] KerbolPlus
* [ ] Kopernicus
* [ ] KScale2
* [ ] KSP-64k
* [ ] KSP-64k-12HourDay
* [ ] NewHorizons
* [ ] OuterPlanetsMod
* [ ] RealSolarSystem
* [ ] RhatssPlanetPack
* [ ] SentarExpansion
* [ ] SigmaBinary-core
* [ ] SigmaStockRecolor

**Outdated packs:**
* DunaPlus
* EvePlus
* ForgottenWorlds
* Insystem
* InterstellarAdventure
* KiriusPlanetPack
* TerrestrialPlanetPack

**Comment by Olympic1** [comment]
If I use `{ "name": "Kopernicus", "min_version": "1:beta-02-4", "max_version": "1:beta-02-4" }
` will it then only download v0.2.4?

This is for if a new version comes out (what it just did), it can be that some planet packs don't work on the newest version of Kopernicus. So they'll only work on a specific version.

**Comment by dbent** [comment]
If you want to specify a single version you can just use `version`, no need for both `min` and `max`.

**But** standard policy is to only restrict the `min_version` unless a mod is explicitly known to be incompatible with newer versions of a dependency.

**Comment by plague006** [comment]
Just want to throw out: as we remove the `provides` and `conflicts` relationships for `PlanetPack` it would be nice to have `PlanetPack` added as a `comment` to help track these similar mods down in cases of: large-scale `Kopernicus` change, someone wanting to create a planets metapackage, etc.

**Comment by Dazpoet** [comment]
A planets metapackage O_o

Imagine the RAM needed for such a thing \o/

**Comment by Olympic1** [comment]
Well @Sigma88 is working on a mod that gives every planet pack their own system so the Kerbol system is left as it is and gives interstellar travel a new meaning in KSP.

**Comment by plague006** [comment]
>A planets metapackage O_o

>Imagine the RAM needed for such a thing \o/

Unity 5, the dream.

**Comment by Sigma88** [comment]
@plague006  thanks :)

**Comment by Olympic1** [comment]
I worked on the files this weekend, will make PR's this week

**Comment by Sigma88** [comment]
If you need any help with GalacticNeighborhood let me know. But if I were you I would wait for a more stable release before putting it into CKAN. I could cause more trouble than it's worth right now. :)

**Comment by pjf** [comment]
I just came here to say you're all wonderful. :)

@Olympic1 : If you're on our IRC channel at all (#ckan on irc.esper.net) then ping me if you spot me around in the next 48 hours so I can give you extra new-contributor thanks?

**Comment by politas** [comment]
I realise this is still in progress, but it sounds like there may be an inintended consequence of the conflict system you're implementing. Just had a poster on the forum thread saying this:

 "Okay, this is weird.

Any Kopernicus planet pack that is incompatible with another planet pack is generally "incompatible" with Kopernicus. CKAN lists the planet packs dependencies and somehow gets into a mess with Kopernicus. Try looking at it. Affects any pack."

**Comment by plague006** [comment]
PlanetPacks seem to be making their way back into the fold. Manual testing by 1 person seems unreasonable.

Any thoughts on a better way to test these? Would there be a reasonably easy way to plug in the `Orbit` section of the .cfg file and have a database of other planets to see if they would conflict?

Or should we essentially just crowd-source the testing to our users and have no `conflicts` unless reported by users? (Or the mod authors)

**Comment by dbent** [comment]
We should assume all packs are compatible unless we know otherwise.

**Comment by Olympic1** [comment]
@plague006 I will keep doing this task but any help is appreciated.

I always check the `Orbit` and `Properties` sections to see if it will conflict before I start up KSP. If these do not conflict I visually test it by timewarping it for a couple of years.

I also check the forum thread and download pages to see it the mod author mentions conflicts or if it specifically added support for another pack.

**Comment by Sigma88** [comment]
@plague006  since GalacticNeighborhood basically allows for all planet packs to be loaded at the same time, I would not put an incompatibility tag on any pack. (unless you can ignore that incompatibility when GN is installed)

the only packs that are not compatible even in GN (afaik) will be:
- **KerbolPlus** vs **KPlus Remade** (if the former still exists)
- **RSS** vs **SASS** (when SASS will be made compatible with GN)

I used "will be" because right now I'm still working on a GN update for 1.0.5

**Comment by dbent** [comment]
> @plague006 since GalacticNeighborhood basically allows for all planet packs to be loaded at the same time

Interesting, very neat.

> I would not put an incompatibility tag on any pack. (unless you can ignore that incompatibility when GN is installed)

 Unfortunately, there's currently no way to make relationships conditional, although it's been proposed in [some places](https://github.com/KSP-CKAN/CKAN/issues/1104#issuecomment-111377723). In such a world we could do something like (very rough syntax):

```json
{
    "identifier": "BigKerbin",
    "conflicts": [
        {
            "name": "SmallKerbin",
            "condition": {
                "not_installed": [
                    { "name": "GalacticNeighborhood" }
                ]
            }
        }
    ]
}
```
A theoretically equivalent syntax would be:
```json
{
    "identifier": "BigKerbin",
    "depends": [
        {
            "name": "GalacticNeighborhood",
            "condition": {
                "installed": [
                    { "name": "SmallKerbin" }
                ]
            }
        }
    ]
}
```

However, that's a long ways off. Maintaining `conflcits` will prevent CKAN users for effectively using GalacticNeighborhood which is bad. Right now there's two things I think we can do:

- Remove all `conflicts` and let users handle it, undoing much of the hard work @Olympic1 has done, but you know, [sunk costs](https://en.wikipedia.org/wiki/Escalation_of_commitment) and all that.
- Or, for every planet plack `Foo` create an alternate metadata entry `Foo-GalacticNeighborhood` that `depends` on `GalacticNeighborhood`, `conflicts` with `Foo`, and has no planet pack `conflicts` except those special cases @Sigma88 mentioned above. Unfortunately this effectively doubles the work required to maintain metadata for planet packs which I think is even worse than dropping the `conflicts` @Olympic1 has already added.

Thoughts?

**Comment by Sigma88** [comment]
if not including GN in CKAN is the easiest option for you guys feel free to do that, I won't complain :)
ultimately it's your time and I don't want to create problems with my mod
and the same goes for SASS :D since that one will be even a bigger nightmare I suppose

**Comment by dbent** [comment]
Well the issue is even if GN isn't in CKAN and users install it manually our metadata will still say that two packs will be in conflict when they're not (so long as GN in installed).

In fact, having GN in CKAN would be advantageous because at least it would allow things like my second point above with `-GalacticNeighborhood` metadata (medium term) or conditional relationships (long term).

Also, what's SASS? The only SASS I'm familiar with is a [CSS preprocessor language](http://sass-lang.com/) and I'm assuming this is some kind of alternative to RSS?

**Comment by Sigma88** [comment]
@dbent it's a weird idea I had, basically it rearranges the stock planets and some planets from different planet packs in order to recreate the Solar System, but using stockalike bodies (hence the name, Stock-alike Solar System) here's a link to the [repository](https://github.com/Sigma88/Stockalike) and [forum thread](http://forum.kerbalspaceprogram.com/index.php/topic/131405-/)

**Comment by dbent** [comment]
Cool, I may look into that whenever I get around to actually *playing* KSP again.

**Comment by Sigma88** [comment]
@dbent  lol, last time I played they had just introduced contracts :D

**Comment by plague006** [comment]
The <planetpack>-GH.netkan idea doesn't sound like too much extra work if there were a way to direct the -GH.netkan back to <PP>.netkan (as a metanetkan) and modify the name, abstract, and (here's the kicker) add the GH dependency without overwriting the existing ones.

**Comment by plague006** [comment]
I think as it stands we're proceeding with a "compatible unless we hear otherwise" approach to planetpack conflicts. We can re-open this issue in NetKAN if it seems relevant.

@Sigma88: I noticed Galactic Neighborhood has a 1.1 release on GitHub, want me to whip up a netkan for it?

**Comment by Sigma88** [comment]
@plague006  my approach to CKAN is: if there's someone that wants to take care of it, feel free :)

if you need any help from me (explaining stuff or fixing messed up .version files) feel free to ping me
