### ISSUE TITLE
OPT and Mk3 mini expansion conflict

### ISSUE THREAD

**Issue by Skarllath** [KSP-CKAN/CKAN-meta#592]
OPT Space Plane Parts and Mk3 Mini Expansion pack both attempt to install the same Mk3 Airliner Cockpit.
(Both mods have the same author, kyeon)

File           : GameData/OPT/Parts/mk3_cockpit/mk3_cockpit.cfg
Installing Mod : OPTSpacePlaneParts V1.6.9.1
Owning Mod     : Mk3MiniExpansionPack
CKAN Version   : v1.6.22-0-g007717d (beta)

**Comment by Dazpoet** [comment]
Are you by any chance using KSP 0.90 and/or have recently updated from 0.90 and kept your mods around? There is an issue with this in the metadata for 0.90 in accordance with https://github.com/KSP-CKAN/NetKAN/issues/1248 but it was confined to that version by https://github.com/KSP-CKAN/NetKAN/pull/1087

**Comment by Skarllath** [comment]
No, I'm playing on a fresh install of 1.0.2. 
I think this may be because the two parts in the Mk3 expansion are also in OPT.

**Comment by Dazpoet** [comment]
Ooh I see now it is spaceplaneparts and not mk3miniexpansion. Yes this looks like a packaging error which we need to fix.

**Comment by plague006** [comment]
@Skarllath Sorry this took so long to resolve. You're probably on to 1.0.4 by now, but I was clearing out old issues and now anyone still using 1.0.2 won't run into the same issue as you. =)
