### ISSUE TITLE
Problem with Kerbin Side Air Race 1.2

### ISSUE THREAD

**Issue by Seaview123** [KSP-CKAN/CKAN-meta#593]
Hello, and thanks for creating and updating the CKAN, it's amazingly helpful. 
I had this message when trying to load this mod. Hope this helps to fix it.

File           : GameData/KerbinSide/licence.txt
Installing Mod : KerbinSideAirRace 1.2
Owning Mod     : KerbinSide
CKAN Version   : v1.6.22-0-g007717d (beta)

**Comment by Olympic1** [comment]
This is fixed
