### ISSUE TITLE
Heat Control now allegedly works with DRE

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/CKAN-meta#599]
According to http://forum.kerbalspaceprogram.com/threads/124391-1-02-Heat-Control-Manage-your-ship-s-heat%21-%2815-06-2015-new-radiators-and-heat-exchangers%29?p=2019917&viewfull=1#post2019917 this mod is now DRE-compatible. Apologies if this has already been spotted and is being implemented.

**Comment by dbent** [comment]
Implemented in KSP-CKAN/NetKAN#1619
