### ISSUE TITLE
Telemachus 1.4.29.0 does not exist, installation hangs

### ISSUE THREAD

**Issue by dragonfi** [KSP-CKAN/CKAN-meta#604]
The download link for 1.4.29.0 is invalid.

I can manually download 1.4.29, but 1.4.29.0 gives a 404 error.

The valid version is also added to CKAN-meta, but is overshadowed by 1.4.29.0,
so the installation hangs at the download step.

(I'm not sure if it is a CKAN-meta or a NetKan issue.)

Relevant Pull Request: #603

Note: It needs a review, I don't know if I'm doing this right.

**Comment by dragonfi** [comment]
Update: PR merge solved the problem.

(There might still be a bug in NetKAN though, if the problem resurfaces.)

**Comment by Dazpoet** [comment]
Closing this for now, if the problem resurfaces we can re-open this and/or a new issue
