### ISSUE TITLE
Some of my mods haven't been updated on CKAN

### ISSUE THREAD

**Issue by malahx** [KSP-CKAN/CKAN-meta#666]
Hello, I've updated 5 days ago all my mods to KSP 1.0.4 and 3 of them haven't been updated on CKAN. I don't know what I can do?

QuickRevert [v2.11 - 2015.06.26]: 
* https://kerbalstuff.com/mod/237
* https://github.com/KSP-CKAN/CKAN-meta/tree/master/QuickRevert
* https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/QuickRevert.netkan

QuickMute [v1.06 - 2015.06.26]: 
* https://kerbalstuff.com/mod/509/QuickMute
* https://github.com/KSP-CKAN/CKAN-meta/tree/master/QuickMute
* https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/QuickMute.netkan

QuickContracts [v1.02 - 2015.06.25]: 
* https://kerbalstuff.com/mod/539/QuickContracts
* https://github.com/KSP-CKAN/CKAN-meta/tree/master/QuickContracts
* https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/QuickContracts.netkan

**Comment by dbent** [comment]
NetKAN is failing to parse the embedded AVC `.version` files. In each case, it's failing to parse because there's no comma between the `DOWNLOAD` and `VERSION` properties. There's an open issue (KSP-CKAN/CKAN#1199) to handle this situation more gracefully.

**Comment by malahx** [comment]
Thanks for the answer, I will update my .version files on my next mods update.
