### ISSUE TITLE
ohmygosh! is this a glitch?

### ISSUE THREAD

**Issue by ololosha228** [KSP-CKAN/CKAN-meta#681]
hey!

today? i instal something new mods for my lovest game ever, and...
https://pp.vk.me/c625726/v625726746/44ae5/51twlSC3Xt4.jpg

i have one question: what the fuck is this? :D really, i dont, what is it, but i thing, this is a few wrong.

thank you for you program very much! I like mods, and your program is cooler than any mod manager! big thanks ^____^

**Comment by plague006** [comment]
Re-install HotRockets, then you won't have that issue.

**Comment by dbent** [comment]
A simple update/refresh to get the latest metadata should do. Let us know if you're still having trouble.
