### ISSUE TITLE
Solver engine won't update, file conflict

### ISSUE THREAD

**Issue by Ratzap** [KSP-CKAN/CKAN-meta#682]
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File : GameData/SolverEngines/SolverEngines.version
Installing Mod : SolverEngines v1.5
Owning Mod : ModuleAnimateEmissive
CKAN Version : v1.10.0-0-gb447380 (beta)

Your GameData has been returned to its original state.

**Comment by plague006** [comment]
There was an issue with ModuleAnimateEmissive-v1.4. Re-install Animate Emissive (ModuleAnimateEmissive) and then you should be able to install SolverEngines without issue.

**Comment by plague006** [comment]
KSP-CKAN/NetKAN #1835 should have resolved this for you, if it didn't please re-open the issue and let us know.
