### ISSUE TITLE
Packaging bug? KerbinSide 1.0.3

### ISSUE THREAD

**Issue by LitaAlto** [KSP-CKAN/CKAN-meta#706]
File           : GameData/KerbinSide/Flags/alphastrikelogo.png
Installing Mod : KerbinSide 1.0.3
Owning Mod     : KerbinSideAirRace
CKAN Version   : v1.10.0-0-gb447380 (beta)

**Comment by plague006** [comment]
Thanks for the report, I'm working on it now.

**Comment by plague006** [comment]
When the fix is merged, this issue will close. A few hours after that the bots should push the update through the system. If the issue persists after all that occurs, feel free to reopen the issue.
