### ISSUE TITLE
netkan-bot not updating mods that it should

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN-meta#713]
The two examples currently are:

* FuelTanksPlus not pushing a netkan update (https://github.com/plague006/NetKAN/commit/496ff30de14a74dd52382715452b613858025aaa) in addition to missing releases 1.0, 1.0.1, and 1.0.2. https://kerbalstuff.com/mod/529/Fuel%20Tanks%20Plus
* OuterPlanetsMod not pushing through a new release (1.7.2) in spite of the .netkan working fine locally https://kerbalstuff.com/mod/437/Outer%20Planets%20Mod

Pinging @techman83

**Comment by techman83** [comment]
Generate the output and run ckan_validate.py over it. The bot won't commit metadata that doesn't validate.

I'm off for a ride this morning, so I can take a closer look this arvo.

**Comment by techman83** [comment]
KSP-CKAN/NetKAN-bot#27 which is the OuterPlanetsMod is failing validation as I suspected. Unfortunately the logging is a currently a little lackluster ( KSP-CKAN/NetKAN-bot#19 goes a long way to resolve this) and I'll need to check all of them. If our schema doesn't match what's acceptable in reality we probably need to fix that.

**Comment by dbent** [comment]
At some point I'll like to move all the validation that the bot does into NetKAN itself, so that the bot can assume if NetKAN produces any output at all, it's valid. This will also make it easier to test locally.

**Comment by techman83** [comment]
Cool. Though capturing the error on validate is pretty easy when it's separate. If when your doing that look at exit codes we can catch, that'll make reporting on the errors easier.

@plague006 - The NetKAN bot will grab the latest netkan and process these in about 40 minutes, the data should be committed in an hour.

**Comment by plague006** [comment]
Closed by https://github.com/KSP-CKAN/CKAN/pull/1324 I think? Reopen if I'm mistaken. =)
