### ISSUE TITLE
Oh no! We tried to overwrite a file owned by another mod

### ISSUE THREAD

**Issue by hobnob11** [KSP-CKAN/CKAN-meta#733]
Please including the following information in your report:

File           : GameData/FederalProductions/Flags/FP logo2.png
Installing Mod : DockingTarget 0.1
Owning Mod     : ClampOTronAPAS
CKAN Version   : v1.12.0-0-g0862b9b (beta)

Your GameData has been returned to its original state.

**Comment by plague006** [comment]
Thanks for reporting this, I'll have it fixed within 4 hours (time for me to apply the fixes and the bots to do their things on schedule).

For best results you'll want to re-install `ClampOTronAPAS`, but if that's inconvenient you can install `DockingTarget` but when prompted with recommendations, make sure `FederalProductions Flags` is not selected.

**Comment by plague006** [comment]
If the issue persists 3 hours from now, please comment and I'll re-open the ticket (though I'm certain it's fixed by https://github.com/KSP-CKAN/NetKAN/pull/2050)
