### ISSUE TITLE
Older versions of ModuleManager don't have working download links

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN-meta#750]
Pinging @sarbian hoping you have links to the older versions of ModuleManager. Specifically for 2.4.X and 2.5.X.

**Comment by sarbian** [comment]
Builds before May have all the old one in their artifact but I removed that from newer builds. I don't plan to archive old versions.
If you want them get them there but they won't stay forever ( https://ksp.sarbian.com/jenkins/job/ModuleManager/86/artifact/ )

And why is this on the CKAN tracker ?

**Comment by plague006** [comment]
I created the issue in CKAN-meta because it affects Jenkins trying to build for old ksp versions. Seeing as I directed the question directly to you though, I should have created the issue in your repo. I'm blaming the whole thing on it being ~5am when I wrote it.

Thanks for the link. =)
