### ISSUE TITLE
NewHorizons Not Up to Date

### ISSUE THREAD

**Issue by PyroChiliarch** [KSP-CKAN/CKAN-meta#767]
I hope this is the right spot for this
Meta files say its v0.90
but http://kerbal.curseforge.com/ksp-mods/230099-new-horizons/files says v1.0.4

**Comment by plague006** [comment]
It seems that the way the mod was packaged after version 1.35 changed and that affected our ability to index the mod. The information we currently have is correct, version 1.35 of NewHorizons is made for ksp_version 0.90. We need to index the newer versions of this mod (which are compatible with 1.0.4).

Thanks for bringing this to our attention, it'll be addressed as soon as possible.
