### ISSUE TITLE
Civilian Population:  Wrong version being downloaded.  

### ISSUE THREAD

**Issue by rabidninjawombat** [KSP-CKAN/CKAN-meta#771]
On a 1.04 install. when Trying to download Civilian Population,  it is downloading version 1.7,   This version is over 3 months old.  

The mod is updated via Kerbalstuff, and it should be synced with CKAN.   Current version is 1.7.4.1    Any help resolving this would be legendary.  ( i see the 1.7.4.1 netkan file in the Netkan repository)  but its not downloading,  

Not a CKAN expert,  but trying to avoid support issues from people using old version >_< 

Kerbalstuff stats show hundreds of 1.7 downloads (so i know its not just me heh)  

Thanks for any help you can provide.

**Comment by techman83** [comment]
@rabidninjawombat http://status.ksp-ckan.org/ shows it to have been indexed in the last 2 days. I just refreshed my CKAN and it's showing 1.7.4.1 as the latest available version. There have been a whole bunch indexed in the last couple of months.

**Comment by rabidninjawombat** [comment]
@techman83   Yes,  i know it indexed the latest version,  Not sure what combination of of factors is causing it to download 1.7, but testing it on my my own KSP client generated a 1.7 download,  (did it again after clearing out GAMEDATA folder and getting a 1.7.4.1 download. 

Not sure why, i was able to repo it a couple times, after removing and reinstalling via ckan. Coulda been a PEBCAK on my behalf :P So if everything looks good on your end, then I wont worry about it unless i get tons of issues popping up.

**Comment by plague006** [comment]
No updates in ~1 month. Closing this but will re-open if there are new developments.
