### ISSUE TITLE
Help creating metadata file

### ISSUE THREAD

**Issue by gracae86** [KSP-CKAN/CKAN-meta#773]
hi, I am trying to follow the steps in the wiki but am having some issues. My mod is currently on Kerbal Stuff, but i did not check the CKAN box when I first published the mod. 

1.) the first step states "Copy paste the following into a new file titled <identifier>.netkan"
--what program do i use to create the .netkan file?

2.) is there a special way to package the .zip files on kerbal stuff? Right now I have it as CxAerospace - Station Parts Pack v<version>.zip that contains "GameData\CxAerospace\Station Parts"
--do I need to include the install stanza in the metadata file?

currently I have the following in a .txt file
{
    "spec_version" : 1,
    "identifier"   : "CxAerospace",
    "$kref"        : "#/ckan/kerbalstuff/922",
    "x_netkan_license_ok": true
}

thank you for any direction.

-Chris

**Comment by plague006** [comment]
1) Notepad works just fine
2) With your mod packaged as it currently is, there's no need for an install stanza.

If you want me to create the file/pull request I'd be happy to, but if you want the satisfaction of completing every step of the process it's not something I want to deny you. :smile: 

From this point if you want to create the pull request you'll want to head over to the [NetKAN repository](https://github.com/KSP-CKAN/NetKAN) then click on the `NetKAN` folder. At this point you're looking for the + (plus) link that you can click in the navigation section of the page (NetKAN/NetKAN/ +). From there you can copy+paste your work and keep hitting the green buttons.
