### ISSUE TITLE
RemoteTech_Settings.cfg collisions.

### ISSUE THREAD

**Issue by LebedevRI** [KSP-CKAN/CKAN-meta#775]
File `RemoteTech_Settings.cfg` is being installed by:
* (none? autogenerated?)
* *RemoteTech RSS Configuration* (note that description says: ``... Manually remove RemoteTech/RemoteTech_Settings.cfg first``)
* *Realism Overhaul* (and it has basically the same content as RemoteTech RSS Configuration)

So, if you install *RO* + *RemoteTech*, you'll get all the stations from *RSS*, even if *RSS* is not installed.
Since *RSS* is not a required module for *RO*, i think, *RO* should not install *RSS* version of `RemoteTech_Settings.cfg`

Traditional ```*-configs (virtual)``` approach should work best here, IMO.
Or *RSS* version of `RemoteTech_Settings.cfg` should not re-use stock **Mission control** GUID - 5105f5a9-d628-41c6-ad4b-21154e8fc488, to keep then co-installable.

Also, *KSC Switcher* contains similar list, and it should probably re-use/be aware of/etc of stations listed in `RemoteTech_Settings.cfg`.

**Comment by plague006** [comment]
RO does their own metadata, so you'll need to submit this issue to them. https://github.com/KSP-RO/RealismOverhaul

**Comment by LebedevRI** [comment]
In https://github.com/KSP-RO/RealismOverhaul/issues/568 i was assured that it is already fixed, and will be in next release.
So i guess, this issue can be closed, preferably once next RT && RO && RSS versions hit CKAN :)

**Comment by plague006** [comment]
Closing this now as opposed to the next release as KSP-RO regulates every aspect involved in this issue.
