### ISSUE TITLE
Conflict Buffalo: NASA Inspired MSEV - Explore In Style!  and oder angel125 mods

### ISSUE THREAD

**Issue by www2000** [KSP-CKAN/CKAN-meta#782]
Hi i just found out that there is a problem with the Buffalo: NASA Inspired MSEV and oder mods from angel125.
Here is the log file:

About to install...

 * Pathfinder 0.8.8(cached)
 * WildBlueTools 1.0.19(cached)

Module "Pathfinder" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/WildBlueIndustries/000WildBlueTools/Agencies/WildBlueFlag.png
Installing Mod : WildBlueTools 1.0.19
Owning Mod     : Buffalo
CKAN Version   : v1.14.3-0-g652be65 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by plague006** [comment]
This was discovered a day ago and a fix is pending review but thanks for the report, they're always appreciated.

https://github.com/KSP-CKAN/NetKAN/pull/2434
