### ISSUE TITLE
CKAN error

### ISSUE THREAD

**Issue by JamesB84** [KSP-CKAN/CKAN-meta#783]
Hey everyone, I had an issue trying to update two mods and CKAN told me to report the following information: 

File           : GameData/UmbraSpaceIndustries/CHANGELOG.txt
Installing Mod : Karbonite 0.6.5.0
Owning Mod     : UKS
CKAN Version   : v1.14.3-0-g652be65 (beta)
Thanks for your help! Edit: I'm thinking now that I am looking at this that maybe I should contact RoverDude too. Would that be a fair assessment?

**Comment by JamesB84** [comment]
I'm thinking now that I am looking at this that maybe I should contact Roverdude too. Would that be a fair assessment?

**Comment by plague006** [comment]
A quickfix is in place now which removes Karbonite 0.6.5.0 and instead has users install the previous version.

Don't contact RoverDude, he's aware. His mods are undergoing a full restructure and it'll take a little 
while for CKAN to adapt around it.
