### ISSUE TITLE
 Oh no! We tried to overwrite a file owned by another mod!

### ISSUE THREAD

**Issue by toguspyder** [KSP-CKAN/CKAN-meta#784]
File           : GameData/UmbraSpaceIndustries/CHANGELOG.txt
Installing Mod : Karbonite 0.6.5.0
Owning Mod     : UKS
CKAN Version   : v1.14.3-0-g652be65 (beta)

0.1.0 - 2015.10.16
------------------
Broke USI_Core out from the USITools DLL
Moved nuclear reactors to Advanced Science Tech in the stock tech tree, and Nuclear Power/ Large Nuclear Power in CTT
Bundled container CTT configs from MKS
Moved KIS kontainers into appropriate CTT nodes
Swapped DepletedUranium for DepletedFuel in reactors and containers

**Comment by Olympic1** [comment]
Duplicate of #785
