### ISSUE TITLE
Can't install UKS because it overwrites files.

### ISSUE THREAD

**Issue by shult12** [KSP-CKAN/CKAN-meta#785]
GameData/UmbraSpaceIndustries/CHANGELOG.txt
Installing Mod : UKS 0.31.11.2
Owning Mod     : Karbonite
CKAN Version   : v1.14.3-0-g652be65 (beta)

**Comment by shult12** [comment]
Happens when installing Karbonite too:
GameData/UmbraSpaceIndustries/CHANGELOG.txt
Installing Mod : Karbonite 0.6.5.0
Owning Mod     : UKS
CKAN Version   : v1.14.3-0-g652be65 (beta)

**Comment by Olympic1** [comment]
With USI Core still not merged, it's currently not possible to install Karbonite and MKS together.
See KSP-CKAN/NetKAN/pull/2392

**Comment by shult12** [comment]
I have done it before.

**Comment by shult12** [comment]
Before Karbonite updated I could do it.

**Comment by plague006** [comment]
A quickfix is in place which will make the previous version of Karbonite the one that will be installed. Roverdude's suite of mods will all need their metadata reworked at once.

**Comment by plague006** [comment]
Oh sorry to be clear, you'll need to uninstall then reinstall Karbonite to have this fix take effect.
