### ISSUE TITLE
Umbra Space Industries update issue

### ISSUE THREAD

**Issue by whiteknight4981** [KSP-CKAN/CKAN-meta#786]
File           : GameData/UmbraSpaceIndustries/Kontainers/CTT.cfg
Installing Mod : UKS 0.31.11.2
Owning Mod     : Karbonite
CKAN Version   : v1.14.3-0-g652be65 (beta)

trying to reinstall all 1.04 compatable mods by RoverDude when trying this i get the above error

**Comment by plague006** [comment]
Uninstall then re-install Karbonite and this issue should clear up. Let us know if that doesn't resolve the situation.

**Comment by Olympic1** [comment]
This is fixed in KSP-CKAN/NetKAN/pull/2476

**Comment by whiteknight4981** [comment]
thank you, i was not able to retry until today.  i am running KSP from
Steam and also ran a file check that discovered one corrupted KSP file and
fixed, before i reinstalled the mod through CKAN

thank you very much
