### ISSUE TITLE
ModuleAnimateEmissive v1.13 flagged as compatible with KSP 1.0.4 -- its not and causes game crash!

### ISSUE THREAD

**Issue by CorvusCorax** [KSP-CKAN/CKAN-meta#834]
json registry includes an incorrect dummy entry for "ModuleAnimateEmissive" v1.13

ModuleAnimateEmissive is included in SolverEngine until version v1.11.
Therefore installing or upgrading ModuleAnimateEmissive will install SolverEngine to version v1.13

SolverEngine v1.13 does no longer include ModuleAnimateEmissive (since unneeded in KSP 1.0.5) and more importantly IS NOT compatible with KSP 1.0.4

ModuleAnimateEmissive will be pulled in by RealFuels which will be pulled in by RealismOverhaul (RP-0)

The crash is only triggered if Procedural Parts is also installed

**Comment by Olympic1** [comment]
This fix is waiting on a merge:
#830 and KSP-CKAN/NetKAN/pull/2642

**Comment by Olympic1** [comment]
Fixed
