### ISSUE TITLE
KerbalPlanetaryBaseSystems has conflicting versions

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN-meta#836]
https://github.com/KSP-CKAN/CKAN-meta/tree/master/KerbalPlanetaryBaseSystems has 0.2.7b, 0.2.8, v0.2.7b and v0.2.8. 0.2.8 has KSP version set at 1.0.4, but v0.2.8 has it as 1.0.5. To make things worse, the mod author appears to have removed 0.2.7b from Kerbalstuff (https://kerbalstuff.com/mod/991/Kerbal%20Planetary%20Base%20Systems)
I'm unsure what needs to be done to clean this up.

**Comment by plague006** [comment]
Thanks for the heads up.
