### ISSUE TITLE
Forum links broken by forum migration, but tool exists

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/CKAN-meta#844]
As you'll see at http://forum.kerbalspaceprogram.com/index.php?/topic/126583-welcome-to-the-new-forums/ all existing forum links have broken (sigh) but there is a tool to find the new thread given the old thread's URL. I suggest a bulk conversion of all homepage links in CKAN metadata which are old-forum links into links of the form http://forum.kerbalspaceprogram.com/showthread.php?t=nnnnnn would save a lot of hassle down the line.

**Comment by Olympic1** [comment]
Thanks for the tip. WIll come usefull in KSP-CKAN/CKAN/issues/1527

**Comment by damerell** [comment]
I hadn't seen that. If you want to close this and put the salient fact in #1527, be my guest.

**Comment by Olympic1** [comment]
Done
