### ISSUE TITLE
Adding "Future Weapons" to CKAN

### ISSUE THREAD

**Issue by Aerolfos** [KSP-CKAN/CKAN-meta#892]
I want to add my mod, Future Weapons (https://kerbalstuff.com/mod/359/Future%20Parts), to CKAN. But apparently you need to be a programmer, so I need help.

**Comment by plague006** [comment]
The KerbalStuff page states `Requires BD Armory, version 0.9.9.1` is this accurate that it is only compatible with `BD Armory, version 0.9.9.1` or does it mean that it is compatible with versions 0.9.9.1 and up?

> I want to add my mod, Future Weapons
Is your mod named Future Weapons, or Future Parts? The title on the KerbalStuff page is Future Parts.

Lastly I want to let you know that while https://github.com/KSP-CKAN/NetKAN/pull/2820 will add your mod to CKAN, you won't see a listing for your mod until such time as there's a 1.0.5-compatible version of BDArmory.

**Comment by Aerolfos** [comment]
It should be and up, as long as there are no too big changes. As it is on kerbalstuff, I will update the mod if something breaks anyway, and that should be automatic on CKAN.
Hm yeah..
