### ISSUE TITLE
Incorrect Max KSP version 

### ISSUE THREAD

**Issue by ABZB** [KSP-CKAN/CKAN-meta#907]
For my mod (under "MK2KSPIIntegration") the CKAN .exe is reporting my latest version (8.8.0, 8.8.1 will be uploaded soon) as having a Max KSP ver. of 1.0.4 (using mod version Version 8.5.0.P-FIXED).

I *think* this may be occuring due to that the name for 8.5.0.P-FIXED is (@ https://github.com/KSP-CKAN/CKAN-meta/blob/master/MK2KSPIIntegration/MK2KSPIIntegration-Version_8.5.0.P-FIXED.ckan) is alphabetically after all of other version numbers, due to its non-standard nomenclature.

Aside from a general solution to this, is it possible to delete that old file?

**Comment by Olympic1** [comment]
Fixed in d8e1ed76db9d34faf135136d4b40c4221f9d6afb
