### ISSUE TITLE
CKAN Error

### ISSUE THREAD

**Issue by andreiec** [KSP-CKAN/CKAN-meta#930]
GameData/NearFuturePropulsion/Extras/ReducedElectricEngineThrust/NFPReducedElectricEngineThrust.cfg
Installing Mod : NearFuturePropulsion-LowThrustEP 0.6.0
Owning Mod     : NearFuturePropulsionExtras
CKAN Version   : v1.16.0-0-g7206ce5 (beta)

**Comment by Olympic1** [comment]
Fixed
