### ISSUE TITLE
 Oh no! We tried to overwrite a file owned by another mod!

### ISSUE THREAD

**Issue by markeisenberg02** [KSP-CKAN/CKAN-meta#937]
GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt
Installing Mod : USI-UKS-Shared 0.1.7.0
Owning Mod     : USI-Kolonization
CKAN Version   : v1.16.0-0-g7206ce5 (beta)

**Comment by Olympic1** [comment]
Fixed
