### ISSUE TITLE
Overwrite error

### ISSUE THREAD

**Issue by eupraxo** [KSP-CKAN/CKAN-meta#940]
CKAN has been great, but tonight when I tried to "update all mods with updates" I got an error I haven't gotten before. Following the instructions I did a ckan update and it went fine. The error during the install phase:

> ```
> About to install...
> 
>  * Sounding Rockets! 0.2.0
>  * USI Freight Transport Technologies 0.4.0
>  * USI Kolonization 0.1.1.0
> 
> Downloading "https://github.com/BobPalmer/SoundingRockets/releases/download/0.2.0/SoundingRockets_0.2.0.zip" (libcurl)
> Downloading "https://github.com/BobPalmer/FTT/releases/download/0.4.0/FTT_0.4.0.zip" (libcurl)
> Downloading "https://github.com/BobPalmer/Kolonization/releases/download/0.1.1.0/Kolonization_0.1.1.0.zip" (libcurl)
> Module "Sounding Rockets!" successfully installed
> Module "USI Freight Transport Technologies" successfully installed
> 
> Oh no! We tried to overwrite a file owned by another mod!
> Please try a `ckan update` and try again.
> 
> If this problem re-occurs, then it maybe a packaging bug.
> Please report it at:
> 
> https://github.com/KSP-CKAN/CKAN-meta/issues/new
> 
> Please including the following information in your report:
> 
> File           : GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt
> Installing Mod : USI-UKS-Shared 0.1.1.0
> Owning Mod     : USI-Kolonization
> CKAN Version   : v1.16.0-0-g7206ce5 (beta)
> 
> Your GameData has been returned to its original state.
> 
> Error!
> 
> ```

**Comment by Olympic1** [comment]
Ths was fixed in https://github.com/KSP-CKAN/CKAN-meta/commit/3f45a6ababed232f498faaee4b17ad606de9f2e0. Refresh your mod list

**Comment by eurpaxo** [comment]
I thanks for the reply. I ran ckan.exe update and also did a manual refresh within the program, but I get a very very similar error, USI-UKS-Shared 0.1.7.0 this time instead of 0.1.1.0:

> ```
> Installing previously uninstalled mod USI-UKS-Shared
> 
> Oh no! We tried to overwrite a file owned by another mod!
> Please try a `ckan update` and try again.
> 
> If this problem re-occurs, then it maybe a packaging bug.
> Please report it at:
> 
> https://github.com/KSP-CKAN/CKAN-meta/issues/new
> 
> Please including the following information in your report:
> 
> File           : GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt
> Installing Mod : USI-UKS-Shared 0.1.7.0
> Owning Mod     : USI-Kolonization
> CKAN Version   : v1.16.0-0-g7206ce5 (beta)
> 
> Your GameData has been returned to its original state.
> 
> Error!
> ```

Thanks.

**Comment by Olympic1** [comment]
Uninstall `USI Kolonization` and then re-install it.

**Comment by eupraxo** [comment]
Uninstall and reinstall, why didn't I think of that. Sheesh. Uninstalled all the USI stuff and reinstalled and it went fine. Thanks for your time!
