### ISSUE TITLE
Impact not providing most recent version due to version naming error

### ISSUE THREAD

**Issue by GraemeCTaylor** [KSP-CKAN/CKAN-meta#941]
CKAN is currently serving up Impact! V1.2.0 rather than the most recent V1.3.0 as the version naming convention between them changed slightly. 

It is considering Impact-1.3.0.ckan as lower version than Impact-**v**1.2.0.ckan (note the extra v).

I don't know the proper way to fix this (delete all earlier ckan files? But I guess that would mess up anyone still using KSP 1.0.4) so I leave the solution to someone better in the know.

**Comment by Olympic1** [comment]
Thx for reporting that, KSP-CKAN/NetKAN/pull/3041 will fix this.
