### ISSUE TITLE
error py updating USI-UKS-Shared

### ISSUE THREAD

**Issue by www2000** [KSP-CKAN/CKAN-meta#942]
Installing previously uninstalled mod USI-UKS-Shared

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt
Installing Mod : USI-UKS-Shared 0.1.7.0
Owning Mod     : USI-Kolonization
CKAN Version   : v1.16.0-0-g7206ce5 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Olympic1** [comment]
Uninstall `USI Kolonization` v0.1.4.0 and `USI Kolonization Core` v0.1.7.0, then try installing `USI Kolonization Core` again.

**Comment by Olympic1** [comment]
@www2000 is it fixed?

**Comment by www2000** [comment]
Fix after a reinstall.
