### ISSUE TITLE
Error installing mod

### ISSUE THREAD

**Issue by marauder13** [KSP-CKAN/CKAN-meta#943]
Thanking you in advance for your time and help.

Requested information as follows.

Installing Mod : USI-UKS-Shared 0.1.7.0
Owning Mod     : USI-Kolonization
CKAN Version   : v1.16.0-0-g7206ce5 (beta)
[CHANGELOG.txt](https://github.com/KSP-CKAN/CKAN-meta/files/125879/CHANGELOG.txt)

**Comment by Olympic1** [comment]
Uninstall `USI Kolonization` and then re-install it.

**Comment by Olympic1** [comment]
@marauder13 is it fixed?

**Comment by marauder13** [comment]
Oops. Sorry. Since the email address contained 'notifications', I thought it was a send only address.

Yes, the issue has been fixed using the process you sent.

Thank you for your help, and for all the work you have put into this application.


Craig.

Date: Sun, 14 Feb 2016 07:59:13 -0800
