### ISSUE TITLE
Science Alert broken in 1.0.5

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/CKAN-meta#945]
It's *still* not working in 1.0.5, and really needs an override to not be available. Yes, there's a manual patch somewhere in the thread, but CKAN needs to not be serving a broken mod.

**Comment by plague006** [comment]
Unable to replicate, cannot install with a 1.0.5 install. ![Screenshot of CKAN 1.16 not being able to install ScienceAlert](http://puu.sh/n5qQR/89448a20bf.png)

According to GitHub none of the files have been edited [in 6 months](https://github.com/KSP-CKAN/CKAN-meta/tree/master/ScienceAlert).

**Comment by NathanKell** [comment]
That confuses me, because I continually get reports from people who install (using CKAN) an RO suite on 1.0.5, and end up with science alert, and then can't transmit. Maybe they are setting CKAN to ignore version or something?

**Comment by plague006** [comment]
No such setting exists (yet).

**Comment by NathanKell** [comment]
So now I am even more confused. Well, closing this then...

**Comment by plague006** [comment]
Is it possible your users installed during 1.0.4 then upgraded to 1.0.5?

**Comment by NathanKell** [comment]
That is possible, although IIRC I've seen "fresh install" reports.
