### ISSUE TITLE
'Kerbalstuff' outages, contingency?

### ISSUE THREAD

**Issue by bgse** [KSP-CKAN/CKAN-meta#946]
Might be just my impression, but Kerbalstuff seems to be increasingly unreliable as of late.

Since a vast amount of packages have at least some dependencies to other packages hosted on KS, this is sort of an 'all eggs in one basket' situation.

What could the first steps towards a contingency plan look like for CKAN-meta?

Related: https://github.com/KSP-CKAN/CKAN/issues/1586

**Comment by plague006** [comment]
Closing in favour of the aforementioned https://github.com/KSP-CKAN/CKAN/issues/1586
