### ISSUE TITLE
Packaging bug for USI

### ISSUE THREAD

**Issue by latenightgames** [KSP-CKAN/CKAN-meta#948]
File           : GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt
Installing Mod : USI-UKS-Shared 0.1.9.0
Owning Mod     : USI-Kolonization
CKAN Version   : v1.16.0-0-g7206ce5 (beta)

**Comment by Olympic1** [comment]
As in previous issues: uninstall and re-install `USI Kolonization`

**Comment by latenightgames** [comment]
Thanks. I've tried uninstalling and reinstalling various bits, but it seems that uninstalling everything associated with USI does the trick.
