### ISSUE TITLE
USI Packaging Bug

### ISSUE THREAD

**Issue by kaesle** [KSP-CKAN/CKAN-meta#950]
File           : GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt
Installing Mod : USI-UKS-Shared 0.1.9.0
Owning Mod     : USI-Kolonization
CKAN Version   : v1.16.0-0-g7206ce5 (beta)

**Comment by Olympic1** [comment]
As in previous issues: uninstall and re-install `USI Kolonization`

**Comment by kaesle** [comment]
That did it. Thanks!
