### ISSUE TITLE
Freeze all mods pointing towards KS dl links

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-meta#956]
I'm going to assume a few things here but I think they'll be correct.

Assumption 1: CKAN won't list mods in the master.zip unless they have a .ckan extension
Assumption 2: CKANs modlist being de-populated is better than it being populated by non-working mods
Assumption 3: We should not, and cannot be allowed to, lose track of all the identifiers we're currently using.

If the above are true I think we (aka someone who know hows how to automate such a thing) should change all mods which have a download field pointing towards a KS link into using a .kerbalstuff extension rather than the current .ckan one. I choose the extension based on https://github.com/KSP-CKAN/NetKAN/pull/3107 so we maintain some kind of system in all the madness.

Pinging @techman83 who was responsible for the NetKAN PR which did something similar.

**Comment by Dazpoet** [comment]
HAving thought about this some more another important assumption should probably be added!

Assumption 4: We won't horribly break everyones installs when the mods they already have installed are suddenly ripped from the next metadataset they download.

**Comment by plague006** [comment]
> We won't horribly break everyones installs when the mods they already have installed are suddenly ripped from the next metadataset they download.

I've been told a couple times that this isn't an issue anymore.

Also want to mention that @techman83 needs to be the person to do this in order to cancel the Jenkins job this will create. (Unless we want to lose Jenkins for the hours it'll take to test the PR..)

**Comment by Dazpoet** [comment]
Pretty sure cancelling the Jenkins job is something any of us can do. Just a matter of logging in and press the stop button or whatever it might be called?

**Comment by plague006** [comment]
> a matter of logging in

And that's where things end for me. =)

**Comment by plague006** [comment]
So on IRC you told me how to log in, and I'm stoked that I can rebuild properly, but even as builds are running I don't see any way to stop the process.

**Comment by techman83** [comment]
@plague006 Sorry I totally missed this. Think I was still recovering from a nasty flu 9 days ago!

You'll see the running jobs on the left panel under 'Build Executor Status', just press the red 'X'.

**Comment by plague006** [comment]
Problem probably exists between chair and keyboard.. but  I'm just not seeing a red X..
http://puu.sh/nqUC2/05fc779725.png
http://puu.sh/nqUBC/16941bfd49.png
http://puu.sh/nqUFT/8b3844436c.png

**Comment by techman83** [comment]
You're quite right. I've tweaked a couple of settings. With great power comes great responsibility :)
